// Bajrang Baan — Complete text by Goswami Tulsidas (~16th century)
// Source: Bajrang Baan (public domain)
// Language: Awadhi (a dialect of Hindi)
// Script: Devanagari
//
// COMPLETE TEXT — 42 verses total
//
export interface BaanVerse {
  id: string
  number: number
  type: 'doha' | 'chaupai'
  awadhi: string
  transliteration: string
  english: string
  commentary?: string
}

export const bajrangBaanVerses: BaanVerse[] = [

  { id: `b0`, number: 0, type: 'doha', awadhi: `निश्चय प्रेम प्रतीति ते, विनय करैं सनमान।
तेहि के कारज सकल शुभ, सिद्ध करैं हनुमान॥`, transliteration: `niścaya prēma pratīti tē, vinaya karaṁ sanamāna |
tēhi kē kāraja sakala śubha, siddha karaṁ hanumāna ||`, english: `With firm faith, love, and devotion, whoever prays to Hanuman with respect — all their auspicious tasks are accomplished by Hanuman.`, commentary: `The opening doha establishes the prerequisites: firm faith (nishchaya), love (prema), trust (pratiiti), and humility (vinaya). Hanuman does not respond to casual or insincere invocation — the devotee must come with complete surrender.` },
  { id: `b1`, number: 1, type: 'chaupai', awadhi: `जय हनुमान संत हितकारी, सुनि लीजै प्रभु अरज हमारी॥`, transliteration: `jaya hanumāna santa hitakārī, suni lījai prabhu araja hamārī ||`, english: `Victory to Hanuman, the benefactor of saints. Please listen to our prayer, O Lord.`, commentary: `Bajrang Baan begins with an appeal to Hanuman's fundamental nature — he exists for the welfare of saints (santa hitakari). The prayer is not casual; it is an 'araja' — an urgent, heartfelt petition.` },
  { id: `b2`, number: 2, type: 'chaupai', awadhi: `जन के काज विलम्ब न कीजै, आतुर दौरि चरित्र न दीजै॥`, transliteration: `jana kē kāja vilamba na kījai, ātura dauri caritra na dījai ||`, english: `Do not delay in the affairs of your devotees. Come running, do not tarry, O Lord of noble character.`, commentary: `The devotee urges Hanuman to act without delay. The phrase 'come running' (atur dauri) conveys urgency — when the devotee calls, Hanuman responds instantly. This is not impatience but the confidence that comes from deep faith.` },
  { id: `b3`, number: 3, type: 'chaupai', awadhi: `जै जै जै हनुमान गुसाईँ, कृपा करहु गुरु देव की नाईँ॥`, transliteration: `jai jai jai hanumāna gusāīṁ, kṛpā karahu gurudēva kī nāīṁ ||`, english: `Victory, victory, victory to Hanuman, the lord of senses. Bestow your grace like the divine guru.`, commentary: `The triple 'jaya' invokes the three worlds, three times, and three states of consciousness. Calling Hanuman 'gusain' identifies him as master of the senses — the one who controls the inner world.` },
  { id: `b4`, number: 4, type: 'chaupai', awadhi: `जै तेज प्रताप बुधि ज्ञाना, जय कपीस तिहुँ लोक उजाना॥`, transliteration: `jai tēja pratāpa budhi jñānā, jaya kapīsa tihu lōka ujānā ||`, english: `Victory to your radiance, glory, wisdom, and knowledge. Victory to the monkey lord who illuminates the three worlds.`, commentary: `Hanuman's qualities are enumerated: radiance (teja), glory (pratap), intelligence (buddhi), and knowledge (jnana). He is not merely strong — he is the most brilliant being in the cosmos.` },
  { id: `b5`, number: 5, type: 'chaupai', awadhi: `जय जय जय धुनि होत अकाशा, सुमिरत होत दुसह दुख नाशा॥`, transliteration: `jaya jaya jaya dhuni hōta akāśā, sumirata hōta dusaha dukha nāśā ||`, english: `The sound of 'victory, victory' echoes through the heavens. Remembering you destroys unbearable suffering.`, commentary: `The celestial 'jaya' dhvani (sound of victory) reverberates through space. The act of remembrance (sumiran) itself destroys suffering — not the words but the consciousness behind them.` },
  { id: `b6`, number: 6, type: 'chaupai', awadhi: `जो यह पाठ करै मन लाई, ता पर होत हनुमत सहाई॥`, transliteration: `jō yaha pāṭha karaMana laī, tā para hōta hanumata sahāī ||`, english: `Whoever recites this with a focused mind, Hanuman becomes their helper.`, commentary: `The key condition: 'mana lai' — with a focused, devoted mind. Mechanical recitation without attention yields limited results. The mind must be fully engaged.` },
  { id: `b7`, number: 7, type: 'chaupai', awadhi: `सूरदास जो तुम्हरो ध्यावै, अंत काल रघुपुर जावै॥`, transliteration: `sūradāsa jō tumharō dhyāvai, anta kāla raghupura jāvai ||`, english: `The poet (Surdas/Tulsidas) who meditates on you goes to Rama's abode at the time of death.`, commentary: `The promise of liberation: meditation on Hanuman ensures passage to Rama's divine abode at death. Hanuman does not keep the devotee for himself — he delivers them to Rama.` },
  { id: `b8`, number: 8, type: 'chaupai', awadhi: `जय अंजनि कुमार बलवंता, शंकर सुवन वीर हनुमंता॥`, transliteration: `jaya añjanī kumāra balavantā, śaṅkara suvana vīra hanumantā ||`, english: `Victory to Anjani's mighty son, the brave Hanuman, offspring of Shiva.`, commentary: `Three identities: Anjani's son (devotion to mother), Shiva's incarnation (divine origin), and mighty hero (courage). These three form the foundation of Hanuman's being.` },
  { id: `b9`, number: 9, type: 'chaupai', awadhi: `बदन कराल काल कुल घालक, राम सहाय सदा प्रतिपालक॥`, transliteration: `badana karāla kāla kula ghālaka, rāma sahāya sadā pratipālaka ||`, english: `Your terrifying face destroys the race of death. With Rama's help, you always protect.`, commentary: `Hanuman's terrifying form destroys death itself (kala). Yet this destruction is protective — he destroys death to preserve life. His power always operates through Rama's grace.` },
  { id: `b10`, number: 10, type: 'chaupai', awadhi: `भूत प्रेत पिशाच निशाचर, अग्नि वेताल काल मारीचर॥`, transliteration: `bhūta prēta piśāca niśācara, agni vētāla kāla mārīcara ||`, english: `Ghosts, spirits, demons, night-walkers, fire-spirits, vampires, death-dealers — `, commentary: `The list of negative entities represents all forms of evil and darkness. In the spiritual sense, these are not just external beings but internal obstacles: fear (bhuta), attachment (preta), delusion (pishacha), and ignorance (nishachar).` },
  { id: `b11`, number: 11, type: 'chaupai', awadhi: `इन्हें मारु तोहि शपथ राम की, राखु नाथ मरजाद नाम की॥`, transliteration: `inhēṁ māru tōhi śapatha rām kī, rākhu nātha marajāda nām kī ||`, english: `Slay them all — I adjure you by the oath of Rama! Protect, O Lord, the honor of Rama's name.`, commentary: `The most powerful invocation in the Bajrang Baan: the devotee takes an oath on Rama's name. This is not blasphemy but the highest form of devotion — using God's own name as leverage to invoke God's own servant. The 'honor of the name' (marajada) means that if Hanuman does not act, Rama's name loses its power.` },
  { id: `b12`, number: 12, type: 'chaupai', awadhi: `जय जय जय धुनि गगन धरणी, सुमिरत होत दुख दारिद भंजन॥`, transliteration: `jaya jaya jaya dhuni gagana dharaṇī, sumirata hōta dukha dārida bhañjana ||`, english: `The sound of 'victory' fills heaven and earth. Remembering you destroys poverty and suffering.`, commentary: `The victory cry fills all of creation — above (gagan) and below (dharani). Hanuman destroys not just spiritual suffering but material poverty (daridya) as well. This is not worldliness but recognition that the divine encompasses all aspects of life.` },
  { id: `b13`, number: 13, type: 'chaupai', awadhi: `जो कोई जोगी जग में जावा, हनुमत तुम ताको सुख पावा॥`, transliteration: `jō kōī jōgī jaga mēṁ jāvā, hanumata tuma tākō sukha pāvā ||`, english: `Whatever yogi exists in the world, O Hanuman, you grant them happiness.`, commentary: `The yogi who meditates receives happiness through Hanuman's grace. This establishes Hanuman as the patron of all spiritual practitioners — not just devotees but yogis, jnanis, and practitioners of every path.` },
  { id: `b14`, number: 14, type: 'chaupai', awadhi: `हनुमत तुम सम कोउ नहिं जाई, जानत शिव विष्णु भगवान॥`, transliteration: `hanumata tuma samā kōu nahīṁ jāī, jānata śiva viṣṇu bhagavān ||`, english: `There is no one equal to you, O Hanuman. This is known by Shiva, Vishnu, and God himself.`, commentary: `This is the highest possible praise: Shiva (the destroyer), Vishnu (the preserver), and the supreme Godhead all acknowledge that Hanuman has no equal. This is not hyperbole but theology — Hanuman, as the perfect devotee, transcends even the gods.` },
  { id: `b15`, number: 15, type: 'chaupai', awadhi: `तुम अस बलि सर्वहिं जग माहीं, राम सहाय सो यश पाहीं॥`, transliteration: `tuma asa balī sarvahiṁ jaga māhīṁ, rāma sahāya sō yaśa pāhīṁ ||`, english: `You are thus the strongest in all the world. With Rama's help, you attain this glory.`, commentary: `Hanuman's strength is acknowledged as supreme in all the world — but the source is always Rama. His glory (yasha) comes from Rama's help, not from independent power. This teaches that true strength comes from alignment with the divine.` },
  { id: `b16`, number: 16, type: 'chaupai', awadhi: `जय रघुनाथ रमापति माता, जय हनुमान जानकी पाता॥`, transliteration: `jaya raghunātha ramāpati mātā, jaya hanumāna jānakī pātā ||`, english: `Victory to Rama, lord of the Raghus, and Lakshmi the mother. Victory to Hanuman, the protector of Sita.`, commentary: `The divine family is invoked: Rama (lord of Raghus), Lakshmi (Ramapati = consort of Rama), and Hanuman as Sita's protector. This cosmic family represents the complete divine order.` },
  { id: `b17`, number: 17, type: 'chaupai', awadhi: `जय जय जय धुनि होत अपारा, सुमिरत होत दुसह दुख दारा॥`, transliteration: `jaya jaya jaya dhuni hōta apārā, sumirata hōta dusaha dukha dārā ||`, english: `The sound of 'victory' echoes without limit. Remembering you destroys even the most terrible suffering.`, commentary: `The triple jaya creates an unlimited (apara) resonance. The 'most terrible suffering' (dusaha dukha) that Hanuman destroys is not ordinary pain but the existential suffering of separation from the divine.` },
  { id: `b18`, number: 18, type: 'chaupai', awadhi: `ताहि अवसर राम कह देखा, तब लगि मोहि परम पद लेखा॥`, transliteration: `tāhi avasara rām kaha dēkhā, taba lagi mōhi parama pada lēkhā ||`, english: `At that moment, seeing Rama, I attained the supreme position.`, commentary: `The devotee, through Hanuman's grace, attains the supreme state (parama pada) — self-realization, liberation, union with the divine. This is the ultimate promise of the Bajrang Baan.` },
  { id: `b19`, number: 19, type: 'chaupai', awadhi: `तुम प्रभु करहु तो दुख हरो, नाथ अधम को उद्धरो॥`, transliteration: `tuma prabhu karahu tō dukha harō, nātha adhama kō uddharō ||`, english: `You are the Lord — remove my suffering. O master, uplift this fallen one.`, commentary: `The devotee calls himself 'adhama' — the lowest, the most fallen. This is not self-hatred but the recognition that without divine grace, the ego keeps us trapped in the lowest states of consciousness. Hanuman's role is to 'uplift' (uddharo) — to pull us up from our self-imposed limitations.` },
  { id: `b20`, number: 20, type: 'chaupai', awadhi: `जय अंजनि कुमार जय बाला, सत्य सनातन धरम की राखा॥`, transliteration: `jaya añjanī kumāra jaya bālā, satya sanātana dharama kī rākhā ||`, english: `Victory to Anjani's son, victory to the young one. You protect the eternal dharma.`, commentary: `Hanuman protects 'satya sanatana dharma' — the eternal, true religion. This is not sectarian but universal: the cosmic order itself is sustained by Hanuman's vigilance.` },
  { id: `b21`, number: 21, type: 'chaupai', awadhi: `जो प्राणी चरित्र तव ध्यावा, हनुमत रूप महा सुख पावा॥`, transliteration: `jō prāṇī caritra tava dhyāvā, hanumata rūpa mahā sukha pāvā ||`, english: `Whatever living being meditates on your character attains great happiness in Hanuman's form.`, commentary: `Meditation on Hanuman's character (charitra) — not just his form — leads to 'maha sukha' — the supreme joy. This teaches that the devotee should contemplate not just what Hanuman looks like, but what he represents: selfless service, perfect devotion, and unwavering courage.` },
  { id: `b22`, number: 22, type: 'chaupai', awadhi: `त्राहि त्राहि हनुमान बाण दुख निवारण, कृपा करहु भगवान॥`, transliteration: `trāhi trāhi hanumāna bāṇa dukha nivāraṇa, kṛpā karahu bhagavān ||`, english: `Save me, save me, O Hanuman, arrow that destroys suffering! Bestow your grace, O God!`, commentary: `The 'Baan' (arrow) in the title refers to this: Hanuman himself is the arrow that destroys suffering. The double 'trahi' (save me) conveys desperate urgency — the devotee is calling for immediate rescue.` },
  { id: `b23`, number: 23, type: 'chaupai', awadhi: `जय हनुमान जय बजरंगी, कृपा करहु मम दीन के संगी॥`, transliteration: `jaya hanumāna jaya bajaṅgī, kṛpā karahu mama dīna kē saṅgī ||`, english: `Victory to Hanuman, victory to Bajrangi. Bestow grace on me, companion of the humble.`, commentary: `Bajrangi — 'one with a body like a diamond' — is invoked. Hanuman is called 'companion of the humble' (dina ke sangi) — he does not favor the powerful but stays with those who are lowly and sincere.` },
  { id: `b24`, number: 24, type: 'chaupai', awadhi: `राम रसायन तुम्हरे पासा, सदा रहो रघुपति के दासा॥`, transliteration: `rāma rasāyana tumharē pāsā, sadā raho raghupati kē dāsā ||`, english: `You possess the elixir of Rama's name. May you forever remain the servant of Rama.`, commentary: `The 'elixir of Rama' (rasayana) is the divine name itself — the ultimate medicine for the disease of samsara. Hanuman carries this not in a vessel but in his heart. The prayer to 'forever remain a servant' is the highest aspiration.` },
  { id: `b25`, number: 25, type: 'chaupai', awadhi: `राम राम रमेश हरि रामा, नाम लेत सुख उपजत विश्रामा॥`, transliteration: `rāma rāma ramēśa hari rāmā, nāma lēta sukha upajata viśrāmā ||`, english: `Rama, Rama, O lord of Rama, Hari, Rama — taking your name, happiness and peace arise.`, commentary: `The divine name itself is repeated: Rama, Rama, Ramesha, Hari, Rama. Each name carries a different aspect of the divine. The act of taking the name (naam leta) creates both happiness (sukha) and rest (vishrama) — the two things the suffering soul needs most.` },
  { id: `b26`, number: 26, type: 'chaupai', awadhi: `हनुमत कृपा बिना रघुनाथ, सिद्धि न होइ गुसाईं नाथ॥`, transliteration: `hanumata kṛpā binā raghunātha, siddhi na hōi gusāīṁ nātha ||`, english: `Without Hanuman's grace, O lord of the Raghus, no perfection is possible, O lord of senses.`, commentary: `This is a theological claim of the highest order: even Rama's devotees need Hanuman's grace. Without the perfect devotee's intercession, even the path to God is blocked. Hanuman is not an optional accessory to the spiritual path — he is essential.` },
  { id: `b27`, number: 27, type: 'chaupai', awadhi: `जय जय जय हनुमान अगाधा, दुख पावत जन तुम्हरो बाधा॥`, transliteration: `jaya jaya jaya hanumāna agādhā, dukha pāvata jana tumharō bādhā ||`, english: `Victory, victory, victory to the unfathomable Hanuman. When devotees are in distress, you are their obstacle-destroyer.`, commentary: `Hanuman is 'agadha' — unfathomable, unfathomable. His depth cannot be measured by the mind. Yet he is utterly accessible to the devotee in distress. The paradox: the most transcendent being is also the most immediately available.` },
  { id: `b28`, number: 28, type: 'chaupai', awadhi: `अंजनि तनय बल शक्ति निधि, नाम तुम्हारो जगत में विदित॥`, transliteration: `añjanī tanaya bala śakti nidhi, nāma tumharō jagata mēṁ vidita ||`, english: `O Anjani's son, treasure of strength and power, your name is renowned throughout the world.`, commentary: `The 'treasure of strength and power' (bala shakti nidhi) is Hanuman's true nature. His name being 'known throughout the world' (jagat me vidita) is not fame but the spreading of divine consciousness through the power of his name.` },
  { id: `b29`, number: 29, type: 'chaupai', awadhi: `बाल समय रवि भक्षि लियो तब, तीनहुं लोक भयो तब अचम्भित॥`, transliteration: `bāla samaya ravi bhakṣi liyō taba, tīnahuṁ lōka bhayō taba acambhita ||`, english: `In childhood, you swallowed the sun. The three worlds were astonished.`, commentary: `The childhood story of Hanuman swallowing the sun is the origin of his power — and also of the curse that made him forget it. The three worlds' astonishment shows that Hanuman's power was recognized from the very beginning of his existence.` },
  { id: `b30`, number: 30, type: 'chaupai', awadhi: `देवन तब हनुमान तुम धायो, उर लियो मारुति धरि भयो॥`, transliteration: `dēvana taba hanumāna tuma dhāyō, ura liyō māruti dhari bhayō ||`, english: `The gods came running to you then, O Hanuman. The Wind God held you to his chest.`, commentary: `The gods rushed to baby Hanuman after the sun incident. The Wind God (Maruti = Hanuman's father) embraced him. This teaches that even the cosmic forces (Vayu, the wind) are expressions of parental love when it comes to the divine child.` },
  { id: `b31`, number: 31, type: 'chaupai', awadhi: `लक्ष्मण मूर्छित पड़े जब, आनन तब तुम व्याकुल होयो॥`, transliteration: `lakṣmaṇa mūrchita paṛē jaba, ānana taba tuma vyākula hōyō ||`, english: `When Lakshmana fell unconscious, you became greatly distressed.`, commentary: `Hanuman's distress at Lakshmana's condition reveals his emotional nature — he is not a cold warrior but a deeply feeling being. His distress becomes the fuel for his most heroic act.` },
  { id: `b32`, number: 32, type: 'chaupai', awadhi: `आनन तब तुम व्याकुल भयो, गरुड़ मंत्र जब लगन लगायो॥`, transliteration: `ānana taba tuma vyākula bhayō, garuṛa mantra jaba lagana lagāyō ||`, english: `You became greatly distressed. Then the Garuda mantra was applied.`, commentary: `When Hanuman was distressed, the Garuda mantra (the sacred syllable that neutralizes all poisons and weapons) was applied. This teaches that even the most powerful beings need divine intervention — no one is self-sufficient.` },
  { id: `b33`, number: 33, type: 'chaupai', awadhi: `जामवंत की सुनि पुकारा, आयो हनुमत तुम दौड़ मारा॥`, transliteration: `jāmavanta kī suni pukārā, āyō hanumata tuma dauṛa mārā ||`, english: `Hearing Jambavan's call, O Hanuman, you came running.`, commentary: `Jambavan's call awakened Hanuman to his forgotten powers. The 'running' is both literal (he rushed) and symbolic (the instant awakening of dormant potential). This is the most dramatic moment in Hanuman's story — the moment he remembered who he was.` },
  { id: `b34`, number: 34, type: 'chaupai', awadhi: `लपट गयो तुम दुख नहिं माना, लंक जरावन कियो बखाना॥`, transliteration: `lapaṭa gayō tuma dukha nahīṁ mānā, laṁka jarāvana kiyō bakhānā ||`, english: `You embraced the fire without feeling pain. You set Lanka ablaze — this is celebrated.`, commentary: `Hanuman's burning tail was meant as punishment by Ravana. But Hanuman felt no pain — the fire of devotion burns hotter than any physical flame. He turned punishment into power, setting Lanka ablaze with his burning tail. This is the ultimate teaching: what the world intends as harm, the devotee transforms into service.` },
  { id: `b35`, number: 35, type: 'chaupai', awadhi: `रावण युद्ध अजान कियो तब, नागकि फाँस सबै जब लगायो॥`, transliteration: `rāvaṇa yuddha ajāna kiyō taba, nāgaki phāṁsa sabai jaba lagāyō ||`, english: `When Ravana made war, the Nagapasha (serpent weapon) was deployed.`, commentary: `Indrajit's Nagapasha (serpent weapon) bound the entire army. This represents the power of karmic bondage — the serpents of past actions that tie us down. Only divine intervention (Garuda, the serpent-eater) can free us.` },
  { id: `b36`, number: 36, type: 'chaupai', awadhi: `राम काज कियो तुम विलम्बा, आयो जब बजरंग तुम तबा॥`, transliteration: `rāma kāja kiyō tuma vilambā, āyō jaba bajaṅga tuma tabā ||`, english: `You accomplished Rama's mission without delay. You came immediately, O Bajrangi.`, commentary: `The Bajrang Baan's central message: Hanuman never delays in Rama's work. His response is instant, his execution is flawless. This is the ideal of divine service — total commitment without hesitation.` },
  { id: `b37`, number: 37, type: 'chaupai', awadhi: `सुनि हनुमत प्रभु मुद्रिका दीन्हीं, राम काज सब तुमने कीन्हीं॥`, transliteration: `suni hanumata prabhu mudrikā dīnhīṁ, rāma kāja sabha tumana kīnhīṁ ||`, english: `Hearing your prayer, the Lord gave you his ring. You accomplished all of Rama's tasks.`, commentary: `Rama's ring — the divine name — was given to Hanuman as proof and as empowerment. With this ring, Hanuman accomplished everything. The ring represents the divine authorization that the true devotee carries.` },
  { id: `b38`, number: 38, type: 'chaupai', awadhi: `राम तुम्हारो मन्त्र है, तुम राम के सेवक राजा॥`, transliteration: `rāma tumharō mantra hai, tuma rāma kē sēvaka rājā ||`, english: `Rama is your mantra. You are the king among Rama's servants.`, commentary: `The ultimate identification: Rama IS Hanuman's mantra — the divine name that Hanuman repeats constantly. And Hanuman is the 'king of servants' — the highest position in the divine hierarchy, which is service itself.` },
  { id: `b39`, number: 39, type: 'chaupai', awadhi: `जय हनुमान जय राम रसायन, जय जय जय धुनि गगन धरणी॥`, transliteration: `jaya hanumāna jaya rāma rasāyana, jaya jaya jaya dhuni gagana dharaṇī ||`, english: `Victory to Hanuman, victory to the elixir of Rama. Victory, victory, victory — the sound fills heaven and earth.`, commentary: `The Bajrang Baan reaches its crescendo: the triple jaya fills all of creation. Hanuman and Rama's name (the elixir) are praised together — they cannot be separated.` },
  { id: `b40`, number: 40, type: 'chaupai', awadhi: `तुलसीदास सदा हरि चेरा, कीजै नाथ हृदय महँ डेरा॥`, transliteration: `tulasīdās sadā hari cerā, kījai nātha hṛdaya mahṁ ḍerā ||`, english: `Tulsidas is forever the servant of Hari. O Lord, make my heart your dwelling place.`, commentary: `Tulsidas signs the Bajrang Baan just as he signed the Chalisa — with the same humble prayer: 'make my heart your home.' The identity does not change: always Hari's servant (cherā).` },
  { id: `b41`, number: 41, type: 'doha', awadhi: `पवन तनय संकट हरन, मंगल मूरति रूप।
राम लखन सीता सहित, हृदय बसहु सुर भूप॥`, transliteration: `pavana tanaya saṅkaṭa harana, maṅgala mūrati rūpa |
rāma lakhana sītā sahita, hṛdaya basahu sura bhūpa ||`, english: `O Son of the Wind, remover of calamities, embodiment of auspiciousness — dwell in my heart along with Rama, Lakshmana, and Sita.`, commentary: `The closing doha is identical to the Hanuman Chalisa's closing — the same surrender, the same prayer. The Bajrang Baan and the Chalisa are two expressions of the same truth: the divine dwells in the heart of the devotee.` },
]

export const bajrangBaanInfo = {
  title: 'Bajrang Baan',
  sanskritTitle: 'बजरंग बाण',
  transliteration: 'Bajaṅga Bāṇa',
  author: 'Goswami Tulsidas',
  language: 'Awadhi',
  period: '~16th century CE',
  verseCount: bajrangBaanVerses.length,
  summary: 'The Bajrang Baan (Arrow of Bajrangi) is a powerful devotional hymn to Lord Hanuman by Tulsidas. Unlike the Chalisa which is primarily devotional, the Baan is a protective invocation — an arrow of prayer directed at Hanuman for immediate protection from all evils, obstacles, and negative forces. It is traditionally recited when facing dire circumstances.',
  theme: 'Protection, courage, divine intervention, the power of Hanuman as the cosmic protector.',
}

export function getBaanVerse(id: string): BaanVerse | undefined {
  return bajrangBaanVerses.find((v) => v.id === id)
}
