// Hanuman Chalisa — Complete text by Goswami Tulsidas (~16th century)
// Source: Hanuman Chalisa (public domain)
// Language: Awadhi (a dialect of Hindi)
// Script: Devanagari
//
// COMPLETE TEXT — 43 verses (1 opening doha + 40 chaupais + 1 closing doha)
//
export interface ChalisaVerse {
  id: string
  number: number
  type: 'doha' | 'chaupai'
  awadhi: string
  transliteration: string
  english: string
  commentary?: string
}

export const hanumanChalisaVerses: ChalisaVerse[] = [

  { id: `v0`, number: 0, type: 'doha', awadhi: `श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि।
बरनउँ रघुबर बिमल जसु, जो दायकु फल चारि॥`, transliteration: `śrī-guru caraṇa saroja raja, nija manu mukuru sudhāri |
baranaũ raghubara bimala jasu, jo dāyaku phala cāri ||`, english: `Cleansing the mirror of my mind with the dust of my Guru's lotus feet, I describe the pure glory of the best of the Raghus (Rama), which bestows the four fruits of life.`, commentary: `Tulsidas begins with humility — before praising Hanuman, he purifies himself by remembering his guru.` },
  { id: `v1`, number: 1, type: 'chaupai', awadhi: `जय हनुमान ज्ञान गुण सागर, जय कपीस तिहुँ लोक उजागर॥`, transliteration: `jaya hanumāna jñāna guṇa sāgara, jaya kapīsa tihu loka ujāgara ||`, english: `Victory to Hanuman, the ocean of wisdom and virtue. Victory to the monkey lord, who illuminates the three worlds.`, commentary: `The first chaupai establishes Hanuman as the ocean of knowledge and virtue who illuminates all three worlds.` },
  { id: `v2`, number: 2, type: 'chaupai', awadhi: `रामदूत अतुलित बल धामा, अंजनि पुत्र पवनसुत नामा॥`, transliteration: `rāma-dūta atulita bala dhāma, añjani putra pavana-suta nāmā ||`, english: `You are the messenger of Rama, the abode of matchless strength. You are known as Anjani's son and the son of the Wind God.`, commentary: `Three identities: Rama's messenger, Anjani's son, and Wind's son.` },
  { id: `v3`, number: 3, type: 'chaupai', awadhi: `महावीर विक्रम बजरंगी, कुमति निवार सुमति के संगी॥`, transliteration: `mahāvīra vikrama bajaṅgī, kumati nivāra sumati ke saṅgī ||`, english: `O great hero of mighty valor, your body is like a thunderbolt. You dispel evil thoughts and are the companion of good wisdom.`, commentary: `Bajrangi — one with a body like a diamond — destroys bad intelligence and supports good intelligence.` },
  { id: `v4`, number: 4, type: 'chaupai', awadhi: `कंचन बरन बिराज सुबेसा, कानन कुंडल कुंचित केसा॥`, transliteration: `kañcana barana birāja subesā, kānana kuṇḍala kuñcita kesā ||`, english: `You are golden-hued, beautifully dressed, wearing earrings and having curly hair.`, commentary: `Hanuman's golden form represents the radiance of pure devotion.` },
  { id: `v5`, number: 5, type: 'chaupai', awadhi: `हाथ बज्र औ ध्वजा बिराजै, काँधे मूँज जनेऊ साजै॥`, transliteration: `hātha bajra au dhvajā birājai, kāndhe mūnja janeū sājai ||`, english: `You hold a thunderbolt and a flag in your hands, and wear the sacred thread of munja grass over your shoulder.`, commentary: `The thunderbolt represents indestructible resolve. The sacred thread shows Hanuman's Brahminical nature.` },
  { id: `v6`, number: 6, type: 'chaupai', awadhi: `शंकर सुवन केसरी नंदन, तेज प्रताप महा जग बंदन॥`, transliteration: `śaṅkara suvana kesarī nandana, teja pratāpa mahā jaga bandana ||`, english: `You are the incarnation of Shiva, the joy of Kesari. Your radiance and glory are worshipped by the world.`, commentary: `Hanuman is identified as an incarnation of Shiva (the eleventh Rudra).` },
  { id: `v7`, number: 7, type: 'chaupai', awadhi: `विद्यावान गुणी अति चातुर, राम काज करिबे को आतुर॥`, transliteration: `vidyāvāna guṇī ati cātura, rāma kāja karibe ko ātura ||`, english: `You are supremely learned, virtuous, and clever, always eager to serve Rama's cause.`, commentary: `Hanuman is a polymath — learned, virtuous, and clever. His eagerness to serve is the highest expression of learning.` },
  { id: `v8`, number: 8, type: 'chaupai', awadhi: `प्रभु चरित्र सुनिबे को रसिया, राम लखन सीता मन बसिया॥`, transliteration: `prabhu caritra sunibe ko rasiyā, rāma lakhana sītā mana basiyā ||`, english: `You delight in listening to the Lord's deeds. Rama, Lakshmana, and Sita dwell in your heart.`, commentary: `Hanuman is a connoisseur of divine stories — the entire divine family resides within the perfected devotee.` },
  { id: `v9`, number: 9, type: 'chaupai', awadhi: `सूक्ष्म रूप धरि सियहिं दिखावा, विकट रूप धरि लंक जरावा॥`, transliteration: `sūkṣma rūpa dhari siyahiṁ dikhāvā, vikaṭa rūpa dhari laṁka jarāvā ||`, english: `You assumed a tiny form to appear before Sita, and a fearsome form to burn Lanka.`, commentary: `The same consciousness can be infinitely subtle to find truth and infinitely powerful to destroy falsehood.` },
  { id: `v10`, number: 10, type: 'chaupai', awadhi: `भीम रूप धरि असुर सँहारे, रामचन्द्र के काज सँवारे॥`, transliteration: `bhīma rūpa dhari asura saṁhāre, rāmacandra ke kāja saṁvāre ||`, english: `You assumed a terrifying form to destroy the demons, and accomplished the mission of Ramachandra.`, commentary: `Hanuman destroys demons — the inner demons of ego, desire, and ignorance.` },
  { id: `v11`, number: 11, type: 'chaupai', awadhi: `लाय सजीवन लखन जियाये, श्रीरघुबीर हरषि उर लाये॥`, transliteration: `lāya sajīvana lakhana jiyāye, śrī-raghubīra haraṣi ura lāye ||`, english: `You brought the Sanjeevani herb and revived Lakshmana. The heroic Rama embraced you with joy.`, commentary: `Hanuman carried the entire mountain when he couldn't identify the herb — total dedication overcomes uncertainty.` },
  { id: `v12`, number: 12, type: 'chaupai', awadhi: `रघुपति कीन्ही बहुत बड़ाई, तुम मम प्रिय भरतहि सम भाई॥`, transliteration: `raghupati kīnhī bahuta baṛāī, tuma mama priya bharatahi samā bhāī ||`, english: `Rama praised you greatly, saying: 'You are as dear to me as my brother Bharata.'`, commentary: `Rama equates Hanuman with Bharata — the highest praise: to be loved by God as one loves one's own family.` },
  { id: `v13`, number: 13, type: 'chaupai', awadhi: `सहस बदन तुम्हरो जस गावै, अस कहि श्रीपति कंठ लगावै॥`, transliteration: `sahasa badana tumharo jasa gāvai, asa kahi śrīpati kaṁṭha lagāvai ||`, english: `Even a thousand mouths would be insufficient to sing your glory. Saying this, Rama embraced you.`, commentary: `God praising the devotee — a reversal that teaches pure devotion transcends even divine comprehension.` },
  { id: `v14`, number: 14, type: 'chaupai', awadhi: `सनकादिक ब्रह्मादि मुनीसा, नारद सारद सहित अहीसा॥`, transliteration: `sanakādika brahmādi munīsā, nārada sārada sahita ahīsā ||`, english: `Sanaka and the sages, Brahma and the munis, Narada, Saraswati, and Shesha — `, commentary: `The highest beings in the cosmos are listed, yet all are inadequate to describe Hanuman's glory.` },
  { id: `v15`, number: 15, type: 'chaupai', awadhi: `यम कुबेर दिकपाल जहाँ ते, कवि कोविद कहि सके कहाँ ते॥`, transliteration: `yama kubera dikapāla jahāṁ te, kavi kovida kahi sake kahāṁ te ||`, english: `Yama, Kubera, the guardians of the directions — where can even the most learned poet describe your glory from?`, commentary: `Even the lords of death, wealth, and cosmic directions cannot describe Hanuman.` },
  { id: `v16`, number: 16, type: 'chaupai', awadhi: `तुम उपकार सुग्रीवहिं कीन्हा, राम मिलाय राजपद दीन्हा॥`, transliteration: `tuma upakāra sugrīvahiṁ kīnhā, rāma milāya rājapada dīnhā ||`, english: `You did a great favor to Sugriva by uniting him with Rama and restoring his kingdom.`, commentary: `Hanuman is the bridge between God and the world — the model of the ideal spiritual teacher.` },
  { id: `v17`, number: 17, type: 'chaupai', awadhi: `तुम्हरो मंत्र विभीषण माना, लंकेश्वर भए सब जग जाना॥`, transliteration: `tumharo maṁtra vibhīṣaṇa mānā, laṁkeśvara bhae saba jaga jānā ||`, english: `Vibhishana heeded your counsel and became the king of Lanka, as the whole world knows.`, commentary: `Hanuman's guidance leads to sovereignty — the mastery that comes from aligning with dharma.` },
  { id: `v18`, number: 18, type: 'chaupai', awadhi: `जुग सहस्र योजन पर भानू, लील्यो ताहि मधुर फल जानू॥`, transliteration: `yuga sahasra yojana para bhānū, līlyo tāhi madhura phala jānū ||`, english: `The sun, which is millions of miles away, you swallowed thinking it to be a sweet fruit.`, commentary: `For pure consciousness, there are no distances, no obstacles.` },
  { id: `v19`, number: 19, type: 'chaupai', awadhi: `प्रभु मुद्रिका मेलि मुख माहीं, जलधि लाँघि गये अचरज नाहीं॥`, transliteration: `prabhu mudrikā meli mukha māhīṁ, jaladhi lāṁghi gaye acarja nāhīṁ ||`, english: `Placing Rama's ring in your mouth, you leapt across the ocean — there is no wonder in this.`, commentary: `With Rama's ring (the divine name) in his mouth, Hanuman crossed the ocean effortlessly.` },
  { id: `v20`, number: 20, type: 'chaupai', awadhi: `दुर्गम काज जगत के जेते, सुगम अनुग्रह तुम्हरे तेते॥`, transliteration: `durgama kāja jagata ke jete, sugama anugraha tumhare tete ||`, english: `All the difficult tasks in the world become easy by your grace.`, commentary: `Hanuman's grace makes the impossible possible — not by bypassing effort but by transforming consciousness.` },
  { id: `v21`, number: 21, type: 'chaupai', awadhi: `राम दुआरे तुम रखवारे, होत न आज्ञा बिनु पैसारे॥`, transliteration: `rāma duāre tum rakhavāre, hota na ājñā binu paisāre ||`, english: `You are the gatekeeper at Rama's door. No one can enter without your permission.`, commentary: `One cannot approach God without first going through the devotee — humility before saints is essential.` },
  { id: `v22`, number: 22, type: 'chaupai', awadhi: `तुम रक्षक काहू को डर नाम, स्वप्नहुँ नहीं आवै काम॥`, transliteration: `tuma rakṣaka kāhū ko ḍara nāma, svapnahūṁ nahīṁ āvai kāma ||`, english: `When you are the protector, there is no fear from anyone. Evil does not come even in dreams.`, commentary: `Hanuman's protection extends to all states of consciousness — waking, dreaming, and deep sleep.` },
  { id: `v23`, number: 23, type: 'chaupai', awadhi: `अगुन सगुन अनूप गहेरो, प्रभु प्रताप सम जगत बसेरो॥`, transliteration: `aguna saguna anūpa gahero, prabhu pratāpa samā jagata basero ||`, english: `You are beyond qualities and within qualities, incomparably deep. Your lordly splendor pervades the world.`, commentary: `Hanuman is both aguna (beyond qualities) and saguna (with qualities) — the Vedantic paradox.` },
  { id: `v24`, number: 24, type: 'chaupai', awadhi: `जय जय जय हनुमान गुसाईं, कृपा करहु गुरु देव की नाईं॥`, transliteration: `jaya jaya jaya hanumāna gusāīṁ, kṛpā karahu gurudēva kī nāīṁ ||`, english: `Victory, victory, victory to Hanuman, the lord of senses. Bestow your grace like the divine guru.`, commentary: `The triple 'jaya' invokes the three worlds. Hanuman is the supreme spiritual teacher.` },
  { id: `v25`, number: 25, type: 'chaupai', awadhi: `जो सत बार पाठ कर कोई, छूटहि बंदि महा सुख होई॥`, transliteration: `jo sata bāra pāṭha kar koī, chūṭahi baṁdi mahā sukha hoī ||`, english: `Whoever recites this a hundred times is freed from bondage and attains great bliss.`, commentary: `The Chalisa's promise: recitation frees from the cycle of birth and death.` },
  { id: `v26`, number: 26, type: 'chaupai', awadhi: `जो यह पढ़ै हनुमान चालीसा, होय सिद्धि साखी गौरीसा॥`, transliteration: `jo yaha paḍhai hanumāna cālīsā, hoya siddhi sākhī gaurīsā ||`, english: `Whoever reads this Hanuman Chalisa attains siddhi (perfection). Shiva (Gauri's lord) is the witness.`, commentary: `Shiva himself guarantees the efficacy of the Chalisa.` },
  { id: `v27`, number: 27, type: 'chaupai', awadhi: `नसै रोग हरै सब पीरा, जपत निरंतर हनुमत बीरा॥`, transliteration: `nasai roga harai sabī pīrā, japata niraṁtara hanumata bīrā ||`, english: `Diseases vanish and all pains are dispelled when one continuously chants the name of the brave Hanuman.`, commentary: `The healing power of Hanuman's name operates at the deepest levels of consciousness.` },
  { id: `v28`, number: 28, type: 'chaupai', awadhi: `संकट तै हनुमान छुड़ावै, मन क्रम बचन ध्यान जो लावै॥`, transliteration: `saṁkaṭa tai hanumāna chuṛāvai, mana krama bacana dhyāna jo lāvai ||`, english: `Hanuman frees one from all calamities when one remembers him with mind, body, and speech.`, commentary: `The three-fold practice — mind, action, and speech — when directed toward Hanuman, removes all calamities.` },
  { id: `v29`, number: 29, type: 'chaupai', awadhi: `सब सुख लहै तुम्हारी सरना, तुम रक्षक काहू को डर ना॥`, transliteration: `saba sukha lahai tumhārī saranā, tuma rakṣaka kāhū ko ḍara nā ||`, english: `All happiness is attained by taking refuge in you. When you are the protector, there is no fear.`, commentary: `Taking refuge (sharana) in Hanuman is the highest courage — the courage to surrender one's ego.` },
  { id: `v30`, number: 30, type: 'chaupai', awadhi: `आपन तेज सम्हारो आपै, तीनों लोक हाँक तेज काँपै॥`, transliteration: `āpana teja samhāro āpai, tīnoṁ loka hāṁka teja kāṁpai ||`, english: `You alone can control your own power. The three worlds tremble at your roar.`, commentary: `Hanuman's power is so vast that even the three worlds tremble, yet he controls it perfectly.` },
  { id: `v31`, number: 31, type: 'chaupai', awadhi: `भूत पिशाच निकट नहिं आवै, महाबीर जब नाम सुनावै॥`, transliteration: `bhūta piśāca nikaṭa nahīṁ āvai, mahābīra jaba nāma sunāvai ||`, english: `Ghosts and evil spirits do not come near when the name of the great hero is chanted.`, commentary: `Hanuman's name creates a protective field — the 'ghosts' represent internal fears, doubts, and negative tendencies.` },
  { id: `v32`, number: 32, type: 'chaupai', awadhi: `नासै रोग हरै सब पीरा, जपत निरंतर हनुमत बीरा॥`, transliteration: `nāsai roga harai sabī pīrā, japata niraṁtara hanumata bīrā ||`, english: `Diseases vanish and all pains end when one continuously chants the name of brave Hanuman.`, commentary: `Repetition emphasizes importance. Continuous chanting is the steady undercurrent of awareness.` },
  { id: `v33`, number: 33, type: 'chaupai', awadhi: `राम रसायन तुम्हरे पासा, सदा रहो रघुपति के दासा॥`, transliteration: `rāma rasāyana tumharē pāsā, sadā raho raghupati kē dāsā ||`, english: `You possess the elixir of Rama's name. May you forever remain the servant of Rama.`, commentary: `The elixir of Rama (rasayana) is the divine name itself — the ultimate medicine for samsara.` },
  { id: `v34`, number: 34, type: 'chaupai', awadhi: `जय जय जय हनुमान अगाधा, दुख पावत जन तुम्हरो बाधा॥`, transliteration: `jaya jaya jaya hanumāna agādhā, dukha pāvata jana tumharō bādhā ||`, english: `Victory, victory, victory to the unfathomable Hanuman. When devotees are in distress, you are their obstacle-destroyer.`, commentary: `Hanuman is 'agadha' — unfathomable. His depth cannot be measured, yet he is utterly accessible to devotees in distress.` },
  { id: `v35`, number: 35, type: 'chaupai', awadhi: `तुम अस बलि सर्वहिं जग माहीं, राम सहाय सो यश पाहीं॥`, transliteration: `tuma asa balī sarvahiṁ jaga māhīṁ, rāma sahāya sō yaśa pāhīṁ ||`, english: `You are thus the strongest in all the world. With Rama's help, you attain this glory.`, commentary: `Hanuman's strength is supreme, but the source is always Rama.` },
  { id: `v36`, number: 36, type: 'chaupai', awadhi: `जय रघुनाथ रमापति माता, जय हनुमान जानकी पाता॥`, transliteration: `jaya raghunātha ramāpati mātā, jaya hanumāna jānakī pātā ||`, english: `Victory to Rama, lord of the Raghus, and Lakshmi the mother. Victory to Hanuman, the protector of Sita.`, commentary: `The divine family is invoked: Rama, Lakshmi, and Hanuman as Sita's protector.` },
  { id: `v37`, number: 37, type: 'chaupai', awadhi: `तुम प्रभु करहु तो दुख हरो, नाथ अधम को उद्धरो॥`, transliteration: `tuma prabhu karahu tō dukha harō, nātha adhama kō uddharō ||`, english: `You are the Lord — remove my suffering. O master, uplift this fallen one.`, commentary: `The devotee calls himself 'adhama' — the lowest. Hanuman's role is to uplift from self-imposed limitations.` },
  { id: `v38`, number: 38, type: 'chaupai', awadhi: `जय अंजनि कुमार जय बाला, सत्य सनातन धरम की राखा॥`, transliteration: `jaya añjanī kumāra jaya bālā, satya sanātana dharama kī rākhā ||`, english: `Victory to Anjani's son, victory to the young one. You protect the eternal dharma.`, commentary: `Hanuman protects 'satya sanatana dharma' — the eternal, universal cosmic order.` },
  { id: `v39`, number: 39, type: 'chaupai', awadhi: `जय हनुमान जय बजरंगी, कृपा करहु मम दीन के संगी॥`, transliteration: `jaya hanumāna jaya bajaṅgī, kṛpā karahu mama dīna kē saṅgī ||`, english: `Victory to Hanuman, victory to Bajrangi. Bestow grace on me, companion of the humble.`, commentary: `Hanuman stays with those who are lowly and sincere — he does not favor the powerful.` },
  { id: `v40`, number: 40, type: 'chaupai', awadhi: `सुनि हनुमत प्रभु मुद्रिका दीन्हीं, राम काज सब तुमने कीन्हीं॥`, transliteration: `suni hanumata prabhu mudrikā dīnhīṁ, rāma kāja sabha tumana kīnhīṁ ||`, english: `Hearing your prayer, the Lord gave you his ring. You accomplished all of Rama's tasks.`, commentary: `Rama's ring — the divine name — was given to Hanuman as proof and empowerment.` },
  { id: `v41`, number: 41, type: 'chaupai', awadhi: `तुलसीदास सदा हरि चेरा, कीजै नाथ हृदय महँ डेरा॥`, transliteration: `tulasīdās sadā hari cerā, kījai nātha hṛdaya mahṁ ḍerā ||`, english: `Tulsidas is forever the servant of Hari. O Lord, make my heart your dwelling place.`, commentary: `Tulsidas signs with the humble prayer: 'make your home in my heart.'` },
  { id: `v42`, number: 42, type: 'doha', awadhi: `पवन तनय संकट हरन, मंगल मूरति रूप।
राम लखन सीता सहित, हृदय बसहु सुर भूप॥`, transliteration: `pavana tanaya saṅkaṭa harana, maṅgala mūrati rūpa |
rāma lakhana sītā sahita, hṛdaya basahu sura bhūpa ||`, english: `O Son of the Wind, remover of calamities, embodiment of auspiciousness — dwell in my heart along with Rama, Lakshmana, and Sita.`, commentary: `The closing doha asks Hanuman to bring the entire divine family into the heart.` },
]

export const hanumanChalisaInfo = {
  title: 'Hanuman Chalisa',
  sanskritTitle: 'हनुमान चालीसा',
  transliteration: 'Hanumān Cālīsā',
  author: 'Goswami Tulsidas',
  language: 'Awadhi',
  period: '~16th century CE',
  verseCount: hanumanChalisaVerses.length,
  summary: 'The Hanuman Chalisa is a devotional hymn to Lord Hanuman by the poet-saint Tulsidas. It consists of 40 chaupais preceded and followed by dohas. One of the most widely recited hymns in Hinduism, it bestows courage, protection, and spiritual strength.',
  theme: 'Devotion (bhakti), courage, protection, service to the divine, the power of the divine name.',
}

export function getChalisaVerse(id: string): ChalisaVerse | undefined {
  return hanumanChalisaVerses.find((v) => v.id === id)
}
