// Yoga Sutras of Patanjali (Pātañjalayogasūtra-s)
// Source: Multiple authoritative references — Sanskrit-TrikaShaivism.com (Gabriel Pradīpaka),
//   WisdomLib.org, SanskritDocuments.org, Edwin Bryant's critical edition
// Total: 4 padas, 196 sutras
//
// Sanskrit: standard Devanagari text (from critical editions)
// Transliteration: IAST (International Alphabet of Sanskrit Transliteration)
// English: based on scholarly translations with clarifications
// Commentary: concise explanations for each sutra

export interface YogaSutraVerse {
  id: string
  number: number
  pada: number
  sanskrit: string
  transliteration: string
  english: string
  commentary?: string
}

export interface YogaPada {
  id: string
  number: number
  name: string
  sanskritName: string
  transliteration: string
  summary: string
  theme: string
  verses: YogaSutraVerse[]
}

// ── Pada 1: Samadhi Pada (51 sutras) ──────────────────────────────────
const samadhiPadaVerses: YogaSutraVerse[] = [
  { id: "1.1", number: 1, pada: 1, sanskrit: "अथ योगानुशासनम्", transliteration: "atha yogānuśāsanam", english: "Now, the instruction of Yoga begins.", commentary: "The word 'atha' (now) marks an auspicious beginning. This sutra introduces the text as a systematic exposition of Yoga, implying the student has prepared through prior study and purification." },
  { id: "1.2", number: 2, pada: 1, sanskrit: "योगश्चित्तवृत्तिनिरोधः", transliteration: "yogaś citta-vṛtti-nirodhaḥ", english: "Yoga is the cessation of the modifications of the mind.", commentary: "This is the foundational definition of Yoga. 'Citta' is the mind-stuff (consciousness), 'vṛtti' are its waves or modifications, and 'nirodhaḥ' is their restraint. When the mind stops identifying with its own fluctuations, the Seer (Puruṣa) abides in its true nature." },
  { id: "1.3", number: 3, pada: 1, sanskrit: "तदा द्रष्टुः स्वरूपेऽवस्थानम्", transliteration: "tadā draṣṭuḥ svarūpe 'vasthānam", english: "Then the Seer abides in its own true nature.", commentary: "When the mind's fluctuations cease, the true Self (Puruṣa, the Seer) is revealed in its essential nature — pure consciousness, beyond all modifications." },
  { id: "1.4", number: 4, pada: 1, sanskrit: "वृत्तिसारूप्यमितरत्र", transliteration: "vṛtti-sārūpyam itaratra", english: "At other times, the Seer identifies with the modifications of the mind.", commentary: "When Yoga is not attained, the Seer mistakenly takes the form of the mind's modifications, identifying with thoughts, emotions, and perceptions instead of remaining in its pure nature." },
  { id: "1.5", number: 5, pada: 1, sanskrit: "वृत्तयः पञ्चतय्यः क्लिष्टा अक्लिष्टाः", transliteration: "vṛttayaḥ pañcatayyaḥ kliṣṭā akliṣṭāḥ", english: "The mental modifications are fivefold, and are either afflicted or non-afflicted.", commentary: "The five vṛttis can be kliṣṭa (causing suffering, rooted in ignorance) or akliṣṭa (not causing suffering, leading toward liberation)." },
  { id: "1.6", number: 6, pada: 1, sanskrit: "प्रमाणविपर्ययविकल्पनिद्रास्मृतयः", transliteration: "pramāṇa-viparyaya-vikalpa-nidrā-smṛtayaḥ", english: "They are: correct knowledge, error, imagination, sleep, and memory.", commentary: "These are the five types of vṛttis. Each arises from specific causes and has specific characteristics. Yoga aims to transcend all five." },
  { id: "1.7", number: 7, pada: 1, sanskrit: "प्रत्यक्षानुमानागमाः प्रमाणानि", transliteration: "pratyakṣānumānāgamāḥ pramāṇāni", english: "The sources of correct knowledge are direct perception, inference, and reliable testimony.", commentary: "Pramāṇa (correct knowledge) comes from three sources: pratyakṣa (direct sense perception), anumāna (logical inference), and āgama (testimony of trustworthy scriptures or teachers)." },
  { id: "1.8", number: 8, pada: 1, sanskrit: "विपर्ययो मिथ्याज्ञानमतद्रूपप्रतिष्ठम्", transliteration: "viparyayo mithyā-jñānam atad-rūpa-pratiṣṭham", english: "Error is false knowledge based on perceiving something as other than what it is.", commentary: "Viparyaya is mistaken cognition — taking something to be what it is not, like mistaking a rope for a snake. It is based on a misapprehension of the object." },
  { id: "1.9", number: 9, pada: 1, sanskrit: "शब्दज्ञानानुपाती वस्तुशून्यो विकल्पः", transliteration: "śabda-jñānānupātī vastu-śūnyo vikalpaḥ", english: "Imagination is a cognitive construction based on words alone, devoid of an actual object.", commentary: "Vikalpa is mental construction not corresponding to reality — like conceptualizing a 'hare's horn' or pondering abstract philosophical ideas without direct reference." },
  { id: "1.10", number: 10, pada: 1, sanskrit: "अभावप्रत्ययालम्बना वृत्तिर्निद्रा", transliteration: "abhāva-pratyayālambanā vṛttir nidrā", english: "Sleep is the mental modification based on the experience of absence or nothingness.", commentary: "Deep sleep (nidrā) is considered a vṛtti because it is a specific state of consciousness, characterized by the absence of other vṛttis while still being an experience." },
  { id: "1.11", number: 11, pada: 1, sanskrit: "अनुभूतविषयासम्प्रमोषः स्मृतिः", transliteration: "anubhūta-viṣayāsampramoṣaḥ smṛtiḥ", english: "Memory is the retention of previously experienced objects without distortion.", commentary: "Smṛti is accurate recollection — the mind reproduces a past experience without adding or subtracting from it. When memory becomes distorted, it becomes viparyaya." },
  { id: "1.12", number: 12, pada: 1, sanskrit: "अभ्यासवैराग्याभ्यां तन्निरोधः", transliteration: "abhyāsa-vairāgyābhyāṁ tan-nirodhaḥ", english: "The cessation of these modifications is achieved through practice (abhyāsa) and detachment (vairāgya).", commentary: "These are the two fundamental methods for attaining Yoga. Abhyāsa is sustained, dedicated practice; vairāgya is the cultivation of non-attachment to objects of desire." },
  { id: "1.13", number: 13, pada: 1, sanskrit: "तत्र स्थितौ यत्नोऽभ्यासः", transliteration: "tatra sthitau yatno 'bhyāsaḥ", english: "Practice is the effort to maintain steadiness of mind.", commentary: "Abhyāsa is not just any practice but specifically the effort to remain in the state of mental stillness. It requires continuous, focused action." },
  { id: "1.14", number: 14, pada: 1, sanskrit: "स तु दीर्घकालनैरन्तर्यसत्कारासेवितो दृढभूमिः", transliteration: "sa tu dīrgha-kāla-nairantarya-satkārāsevito dṛḍha-bhūmiḥ", english: "That practice becomes firmly grounded when it is pursued for a long time, without interruption, and with reverent devotion.", commentary: "Three conditions for successful practice: long duration (dīrgha-kāla), consistency without breaks (nairantarya), and positive, dedicated attitude (satkāra)." },
  { id: "1.15", number: 15, pada: 1, sanskrit: "दृष्टानुश्रविकविषयवितृष्णस्य वशीकारसञ्ज्ञा वैराग्यम्", transliteration: "dṛṣṭānuśravika-viṣaya-vitṛṣṇasya vaśīkāra-saṃjñā vairāgyam", english: "Detachment is the conscious mastery over the craving for objects seen (worldly) or described (heavenly).", commentary: "Vairāgya is the state of being free from thirst (vitṛṣṇa) for both sensory pleasures and higher, even heavenly, rewards. It is not repression but transcendence of desire." },
  { id: "1.16", number: 16, pada: 1, sanskrit: "तत्परं पुरुषख्यातेर्गुणवैतृष्ण्यम्", transliteration: "tat paraṁ puruṣa-khyāter guṇa-vaitṛṣṇyam", english: "The highest detachment is the indifference to the qualities of nature (guṇas) that arises from knowing the true Self (Puruṣa).", commentary: "Para-vairāgya (supreme detachment) arises not from effort but from the direct realization of the Puruṣa as separate from Prakṛti. When you know who you truly are, worldly guṇas lose their hold." },
  { id: "1.17", number: 17, pada: 1, sanskrit: "वितर्कविचारानन्दास्मितारूपानुगमात्सम्प्रज्ञातः", transliteration: "vitarka-vicārānandāsmitā-rūpānugamāt samprajñātaḥ", english: "Samprajñāta samādhi (distinguished concentration) is accompanied by reasoning, reflection, bliss, and the sense of 'I-am-ness.'", commentary: "This is samādhi with a support or seed (sabīja). It progresses through four stages: vitarka (gross reasoning), vicāra (subtle reflection), ānanda (bliss), and asmitā (pure I-consciousness)." },
  { id: "1.18", number: 18, pada: 1, sanskrit: "विरामप्रत्ययाभ्यासपूर्वः संस्कारशेषोऽन्यः", transliteration: "virāma-pratyayābhyāsa-pūrvaḥ saṃskāra-śeṣo 'nyaḥ", english: "The other (asamprajñāta samādhi) is preceded by the practice of stopping all mental activity, leaving only residual impressions.", commentary: "Asamprajñāta samādhi (non-distinguished concentration) is seedless (nirbīja). All mental modifications cease entirely, though subtle latent impressions (saṃskāras) may remain." },
  { id: "1.19", number: 19, pada: 1, sanskrit: "भवप्रत्ययो विदेहप्रकृतिलयानाम्", transliteration: "bhava-pratyayo videha-prakṛti-layānām", english: "The state of those who are disembodied (videhas) or merged in nature (prakṛti-layas) arises from their karma and latent tendencies, not from conscious practice.", commentary: "Some beings reach states resembling samādhi through karmic causes rather than yogic discipline — discarnate beings (videhas) and those merged in primal nature." },
  { id: "1.20", number: 20, pada: 1, sanskrit: "श्रद्धावीर्यस्मृतिसमाधिप्रज्ञापूर्वक इतरेषाम्", transliteration: "śraddhā-vīrya-smṛti-samādhi-prajñā-pūrvaka itareṣām", english: "For others (who strive consciously), it is preceded by faith, energy, mindfulness, concentration, and wisdom.", commentary: "The path for conscious seekers requires five qualities: śraddhā (faith), vīrya (energy/effort), smṛti (mindfulness), samādhi (concentration), and prajñā (discriminative wisdom)." },
  { id: "1.21", number: 21, pada: 1, sanskrit: "तीव्रसंवेगानामासन्नः", transliteration: "tīvra-saṃvegānām āsannaḥ", english: "For those whose intensity is keen, samādhi is near.", commentary: "The speed of attainment depends on the intensity of the aspirant's effort. Those with tīvra-saṃvega (intense spiritual urgency) reach the goal quickly." },
  { id: "1.22", number: 22, pada: 1, sanskrit: "मृदुमध्याधिमात्रत्वात्ततोऽपि विशेषः", transliteration: "mṛdu-madhyādhimātratvāt tato 'pi viśeṣaḥ", english: "There is a further distinction based on whether the intensity is mild, moderate, or extreme.", commentary: "Even among those with intense effort, there are gradations — mild (mṛdu), moderate (madhya), and extreme (adhimātra). The intensity determines the speed of progress." },
  { id: "1.23", number: 23, pada: 1, sanskrit: "ईश्वरप्रणिधानाद्वा", transliteration: "īśvara-praṇidhānād vā", english: "Or else, samādhi is attained through profound devotion to the Lord (Īśvara).", commentary: "Īśvara-praṇidhāna — complete surrender to God — is an alternative path to samādhi. This is the foundation of bhakti yoga within Patañjali's system." },
  { id: "1.24", number: 24, pada: 1, sanskrit: "क्लेशकर्मविपाकाशयैरपरामृष्टः पुरुषविशेष ईश्वरः", transliteration: "kleśa-karma-vipākāśayair aparāmṛṣṭaḥ puruṣa-viśeṣa īśvaraḥ", english: "Īśvara is a distinct, supreme Puruṣa (Self), untouched by afflictions, karma, their results, or the latent traces thereof.", commentary: "Īśvara is a special Puruṣa who is eternally free — never affected by the kleśas (afflictions), karma, its results (vipāka), or the storehouse of impressions (āśaya)." },
  { id: "1.25", number: 25, pada: 1, sanskrit: "तत्र निरतिशयं सर्वज्ञबीजम्", transliteration: "tatra niratiśayaṁ sarva-jña-bījam", english: "In Him, the seed of omniscience has reached its unsurpassable fullness.", commentary: "The 'seed of omniscience' exists in all beings, but in Īśvara it has developed to its fullest, unsurpassed degree. This distinguishes the supreme Puruṣa from bound souls." },
  { id: "1.26", number: 26, pada: 1, sanskrit: "पूर्वेषामपि गुरुः कालेनानवच्छेदात्", transliteration: "pūrveṣām api guruḥ kālenānavacchedāt", english: "He is the teacher of even the ancient teachers, as He is not limited by time.", commentary: "Īśvara is the original Guru — the teacher of even the earliest spiritual teachers — because His knowledge is eternal and not conditioned by temporal limitations." },
  { id: "1.27", number: 27, pada: 1, sanskrit: "तस्य वाचकः प्रणवः", transliteration: "tasya vācakaḥ praṇavaḥ", english: "His symbol/sound-expression is the sacred syllable OṂ (Praṇava).", commentary: "The sound OṂ (Praṇava) is the verbal signifier (vācaka) of Īśvara. It is the most direct sonic representation of the supreme reality." },
  { id: "1.28", number: 28, pada: 1, sanskrit: "तज्जपस्तदर्थभावनम्", transliteration: "taj-japas tad-artha-bhāvanam", english: "The practice consists of the repetition of OṂ and the contemplation of its meaning.", commentary: "Japa (repetition) of OṂ combined with bhāvana (contemplation) of its meaning leads to realization of Īśvara. Both the sound and the inner significance must be united." },
  { id: "1.29", number: 29, pada: 1, sanskrit: "ततः प्रत्यक्चेतनाधिगमोऽप्यन्तरायाभावश्च", transliteration: "tataḥ pratyak-cetanādhigamo 'py antarāyābhāvaś ca", english: "From this practice comes the realization of the individual Self and the removal of obstacles.", commentary: "Īśvara-praṇidhāna leads to: (1) direct knowledge of one's own inner consciousness (pratyak-cetana) and (2) the removal of all obstacles on the path." },
  { id: "1.30", number: 30, pada: 1, sanskrit: "व्याधिस्त्यानसंशयप्रमादालस्याविरतिभ्रान्तिदर्शनालब्धभूमिकत्वानवस्थितत्वानि चित्तविक्षेपास्तेऽन्तरायाः", transliteration: "vyādhi-styāna-saṃśaya-pramādālasya-avirati-bhrānti-darśanālabdha-bhūmikatva-anavasthitatvāni citta-vikṣepās te 'ntarāyāḥ", english: "The obstacles that distract the mind are: disease, mental lethargy, doubt, negligence, laziness, sensuality, false perception, failure to reach a yogic stage, and instability.", commentary: "Nine antarāyas (obstacles) are listed. They range from physical (vyādhi) to mental (styāna, saṃśaya), behavioral (pramāda, ālasya, avirati), perceptual (bhrānti-darśana), and progress-related (alabdha-bhūmikatva, anavasthitatva)." },
  { id: "1.31", number: 31, pada: 1, sanskrit: "दुःखदौर्मनस्याङ्गमेजयत्वश्वासप्रश्वासा विक्षेपसहभुवः", transliteration: "duḥkha-daurmanasya-aṅgamejayatva-śvāsa-praśvāsā vikṣepa-saha-bhuvaḥ", english: "Pain, dejection, restlessness of the body, and irregular breathing accompany the distracting mental projections.", commentary: "These four companions of distraction are symptoms: duḥkha (pain/suffering), daurmanasya (depression), aṅgamejayatva (body tremor), and disturbed breathing patterns." },
  { id: "1.32", number: 32, pada: 1, sanskrit: "तत्प्रतिषेधार्थमेकतत्त्वाभ्यासः", transliteration: "tat-pratiṣedhārtham eka-tattvābhyāsaḥ", english: "To prevent these obstacles, practice should be focused on a single principle.", commentary: "The remedy for all obstacles is ekānta-abhyāsa — steady practice fixed on one truth/principle. This single-pointed focus counteracts mental scattering." },
  { id: "1.33", number: 33, pada: 1, sanskrit: "मैत्रीकरुणामुदितोपेक्षाणां सुखदुःखपुण्यापुण्यविषयाणां भावनातश्चित्तप्रसादनम्", transliteration: "maitrī-karuṇā-muditopekṣāṇāṁ sukha-duḥkha-puṇyāpuṇya-viṣayāṇāṁ bhāvanātaś citta-prasādanam", english: "The mind becomes peaceful by cultivating attitudes of friendliness toward the happy, compassion toward the suffering, joy toward the virtuous, and equanimity toward the unvirtuous.", commentary: "This is one of the most practical teachings in the Yoga Sutras. Four attitudes (bhāvanās) are prescribed for four types of beings: maitrī (friendliness) for the happy, karuṇā (compassion) for the suffering, muditā (joy) for the virtuous, upekṣā (equanimity) for the unvirtuous." },
  { id: "1.34", number: 34, pada: 1, sanskrit: "प्रच्छर्दनविधारणाभ्यां वा प्राणस्य", transliteration: "pracchardana-vidhāraṇābhyāṁ vā prāṇasya", english: "Or else, mental peace can be achieved through controlled exhalation and retention of breath (prāṇāyāma).", commentary: "This introduces prāṇāyāma as a method: pracchardana (exhalation) and vidhāraṇa (retention/stopping) of prāṇa (vital breath)." },
  { id: "1.35", number: 35, pada: 1, sanskrit: "विषयवती वा प्रवृत्तिरुत्पन्ना मनसः स्थितिनिबन्धिनी", transliteration: "viṣayavatī vā pravṛttir utpannā manasaḥ sthiti-nibandhinī", english: "Or else, the arising of a subtle sensory perception that stabilizes the mind.", commentary: "When higher sensory experiences (like visions or subtle perceptions) arise, they can anchor the mind and lead to stability." },
  { id: "1.36", number: 36, pada: 1, sanskrit: "विशोका वा ज्योतिष्मती", transliteration: "viśokā vā jyotiṣmatī", english: "Or else, a luminous, sorrowless perception.", commentary: "Meditation on the inner light (jyoti) that is free from sorrow (viśokā) brings mental stability. This is the light of consciousness itself." },
  { id: "1.37", number: 37, pada: 1, sanskrit: "वीतरागविषयं वा चित्तम्", transliteration: "vīta-rāga-viṣayaṁ vā cittam", english: "Or else, contemplating a mind that is free from all desires.", commentary: "Meditating on the mind of a realized sage — one who is completely free from attraction and aversion — helps stabilize one's own mind." },
  { id: "1.38", number: 38, pada: 1, sanskrit: "स्वप्ननिद्राज्ञानालम्बनं वा", transliteration: "svapna-nidrā-jñānālambanaṁ vā", english: "Or else, using knowledge derived from dream or deep sleep as support.", commentary: "Reflecting on the nature of dream and sleep experiences — which reveal different states of consciousness — can lead to insight and mental stability." },
  { id: "1.39", number: 39, pada: 1, sanskrit: "यथाभिमतध्यानाद्वा", transliteration: "yathābhimata-dhyānād vā", english: "Or else, by meditating on any object of one's own choosing.", commentary: "Patañjali is inclusive: any object of personal inclination can serve as a focus for meditation, provided it leads to steadiness of mind." },
  { id: "1.40", number: 40, pada: 1, sanskrit: "परमाणुपरममहत्त्वान्तोऽस्य वशीकारः", transliteration: "paramāṇu-parama-mahattvānto 'sya vaśīkāraḥ", english: "Mastery extends from the smallest atom to the greatest infinity.", commentary: "When the mind is fully controlled, the yogi can focus on anything — from the subtlest particle (paramāṇu) to the highest magnitude (parama-mahattva)." },
  { id: "1.41", number: 41, pada: 1, sanskrit: "क्षीणवृत्तेरभिजातस्येव मणेर्ग्रहीतृग्रहणग्राह्येषु तत्स्थतदञ्जनता समापत्तिः", transliteration: "kṣīṇa-vṛtter abhijātasyeva maṇer grahītṛ-grahaṇa-grāhyeṣu tat-stha-tad-añjanatā samāpattiḥ", english: "When the mind's modifications are diminished, it becomes like a clear crystal, taking on the form of whatever object is presented — knower, known, or instrument of knowing. This is samāpatti (engrossment).", commentary: "Samāpatti is the state of total mental absorption in which the distinction between subject, object, and act of knowing dissolves." },
  { id: "1.42", number: 42, pada: 1, sanskrit: "शब्दार्थज्ञानविकल्पैः सङ्कीर्णा सवितर्का समापत्तिः", transliteration: "śabdārtha-jñāna-vikalpaiḥ saṅkīrṇā savitarkā samāpattiḥ", english: "Savitarkā samāpatti is the engrossment mixed with the conceptual distinctions of word, meaning, and knowledge.", commentary: "In the initial stage of samāpatti, the mind still operates with concepts — there is still a mixture of word, object, and knowing." },
  { id: "1.43", number: 43, pada: 1, sanskrit: "स्मृतिपरिशुद्धौ स्वरूपशून्येवार्थमात्रनिर्भासा निर्वितर्का", transliteration: "smṛti-pariśuddhau sva-rūpa-śūnyevārtha-mātra-nirbhāsā nirvitarkā", english: "When memory is purified, the mind becomes empty of its own nature and only the object shines forth — this is nirvitarkā samāpatti.", commentary: "In the higher stage, the mind no longer projects its own concepts. Only the object itself remains, in its pure, unmediated presence." },
  { id: "1.44", number: 44, pada: 1, sanskrit: "एतयैव सविचारा निर्विचारा च सूक्ष्मविषया व्याख्याता", transliteration: "etayaiva savicārā nirvicārā ca sūkṣma-viṣayā vyākhyātā", english: "By the same principle, the subtle levels — savicārā (with subtle reflection) and nirvicārā (beyond subtle reflection) — are explained.", commentary: "The same logic applies to subtle objects: savicārā involves reflection on subtle realities, while nirvicārā transcends even that subtle reflection." },
  { id: "1.45", number: 45, pada: 1, sanskrit: "सूक्ष्मविषयत्वं चालिङ्गपर्यवसानम्", transliteration: "sūkṣma-viṣayatvaṁ cāliṅga-paryavasānam", english: "The domain of subtle objects extends up to the unmanifest (aliṅga).", commentary: "Subtle objects of meditation range from the elements to the ego, and ultimately to prakṛti (aliṅga — the unqualified primal nature)." },
  { id: "1.46", number: 46, pada: 1, sanskrit: "ता एव सबीजः समाधिः", transliteration: "tā eva sabījaḥ samādhiḥ", english: "These stages constitute samādhi with seed (sabīja).", commentary: "All the described samāpattis still have a 'seed' — an object of focus. They lead toward but are not yet seedless samādhi." },
  { id: "1.47", number: 47, pada: 1, sanskrit: "निर्विचारवैशारद्येऽध्यात्मप्रसादः", transliteration: "nirvicāra-raiśāradye 'dhyātma-prasādaḥ", english: "When nirvicārā (beyond reflection) is perfected, there is clarity and inner peace.", commentary: "The mind in nirvicārā state attains viśāradī (purity/clarity), leading to adhyātma-prasāda (serenity of the innermost Self)." },
  { id: "1.48", number: 48, pada: 1, sanskrit: "ऋतम्भरा तत्र प्रज्ञा", transliteration: "ṛtaṁ-bharā tatra prajñā", english: "In that state, wisdom is truth-bearing (ṛtaṁbharā).", commentary: "The knowledge that arises in nirvicārā samādhi is ṛtaṁbharā — filled with absolute truth, carrying the direct imprint of reality itself." },
  { id: "1.49", number: 49, pada: 1, sanskrit: "श्रुतानुमानप्रज्ञाभ्यामन्यविषया विशेषार्थत्वात्", transliteration: "śrutānumāna-prajñābhyām anya-viṣayā viśeṣārthatvāt", english: "This truth-bearing wisdom is different from knowledge based on testimony or inference, because it pertains to the particular and essential nature of reality.", commentary: "Inferential and scriptural knowledge is general; the direct knowledge in samādhi is immediate, specific, and experiential." },
  { id: "1.50", number: 50, pada: 1, sanskrit: "तज्जः संस्कारोऽन्यसंस्कारप्रतिबन्धी", transliteration: "taj-jaḥ saṃskāro 'nya-saṃskāra-pratibandhī", english: "The impression (saṃskāra) born from this wisdom prevents the arising of other impressions.", commentary: "The saṃskāra (latent impression) created by ṛtaṁbharā wisdom blocks all other, worldly saṃskāras, gradually purifying the mind." },
  { id: "1.51", number: 51, pada: 1, sanskrit: "तस्यापि निरोधे सर्वनिरोधान्निर्बीजः समाधिः", transliteration: "tasyāpi nirodhe sarva-nirodhān nirbījaḥ samādhiḥ", english: "When even that impression is stopped, and all other modifications cease, seedless (nirbīja) samādhi is attained.", commentary: "The final step: even the subtle impression of truth-bearing wisdom must be transcended. When ALL modifications and impressions are stopped, nirbīja samadhi — liberation itself — is reached." },
]

// ── Pada 2: Sadhana Pada (55 sutras) ──────────────────────────────────
const sadhanaPadaVerses: YogaSutraVerse[] = [
  { id: "2.1", number: 1, pada: 2, sanskrit: "तपःस्वाध्यायेश्वरप्रणिधानानि क्रियायोगः", transliteration: "tapaḥ-svādhyāyeśvara-praṇidhānāni kriyā-yogaḥ", english: "Austerity (tapas), self-study (svādhyāya), and devotion to the Lord (īśvara-praṇidhāna) constitute the yoga of action (kriyā-yoga).", commentary: "Kriyā-yoga is the practical, preparatory yoga consisting of three components: tapas (disciplined practice of austerity), svādhyāya (study of scriptures and self-reflection), and īśvara-praṇidhāna (surrender to the divine)." },
  { id: "2.2", number: 2, pada: 2, sanskrit: "समाधिभावनार्थः क्लेशतनूकरणार्थश्च", transliteration: "samādhi-bhāvanārthaḥ kleśa-tanūkaraṇārthaś ca", english: "Kriyā-yoga is practiced to bring about samādhi and to weaken the afflictions (kleśas).", commentary: "The two purposes of kriyā-yoga are positive (cultivating samādhi) and negative (reducing the five kleśas that cause suffering)." },
  { id: "2.3", number: 3, pada: 2, sanskrit: "अविद्यास्मितारागद्वेषाभिनिवेशाः क्लेशाः", transliteration: "avidyāsmitā-rāga-dveṣābhiniveśāḥ kleśāḥ", english: "The five afflictions (kleśas) are: ignorance, egoism, attachment, aversion, and the fear of death.", commentary: "These are the root causes of human suffering. They form a chain: ignorance gives rise to egoism, which produces attachment/aversion, culminating in the fear of death." },
  { id: "2.4", number: 4, pada: 2, sanskrit: "अविद्या क्षेत्रमुत्तरेषां प्रसुप्ततनुविच्छिन्नोदाराणाम्", transliteration: "avidyā kṣetram uttareṣāṁ prasupta-tanu-vicchinna-udārāṇām", english: "Ignorance (avidyā) is the field for the subsequent afflictions, which may be dormant, attenuated, interrupted, or fully active.", commentary: "Avidyā is the root of all other kleśas. The kleśas manifest in four states: prasupta (dormant), tanu (weakened), vicchinna (alternating/interrupted), and udāra (fully active)." },
  { id: "2.5", number: 5, pada: 2, sanskrit: "अनित्याशुचिदुःखानात्मसु नित्यशुचिसुखात्मख्यातिरविद्या", transliteration: "anityā-aśuci-duḥkhānātmasu nitya-śuci-sukhātma-khyātir avidyā", english: "Ignorance is the mistake of perceiving the impermanent as permanent, the impure as pure, suffering as happiness, and the non-Self as the Self.", commentary: "Avidyā is the fundamental misidentification: taking the temporary for eternal, the impure for pure, pain for pleasure, and what is not the atman for the atman." },
  { id: "2.6", number: 6, pada: 2, sanskrit: "दृग्दर्शनशक्त्योरेकात्मतेवास्मिता", transliteration: "dṛg-darśana-śaktyor ekātmatā ivāsmitā", english: "Egoism (asmitā) is the apparent identification of the power of seeing (Puruṣa) with the power of the instrument of seeing (buddhi).", commentary: "Asmitā occurs when pure consciousness (dṛk, the Seer) mistakenly identifies itself with the intellect (darśana-śakti, the instrument of seeing)." },
  { id: "2.7", number: 7, pada: 2, sanskrit: "सुखानुशयी रागः", transliteration: "sukhānuśayī rāgaḥ", english: "Attachment (rāga) is the clinging to pleasures, following the memory of enjoyment.", commentary: "Rāga arises from the memory of past pleasurable experiences, creating a longing to repeat them." },
  { id: "2.8", number: 8, pada: 2, sanskrit: "दुःखानुशयी द्वेषः", transliteration: "duḥkhānuśayī dveṣaḥ", english: "Aversion (dveṣa) is the repulsion toward painful experiences and their causes.", commentary: "Dveṣa is the opposite of rāga — it is the recoiling from suffering and anything associated with it." },
  { id: "2.9", number: 9, pada: 2, sanskrit: "स्वरसवाही विदुषोऽपि तथा रूढोऽभिनिवेशः", transliteration: "sva-rasa-vāhī viduṣo 'pi tathā rūḍho 'bhiniveśaḥ", english: "The fear of death (abhiniveśa) — the clinging to life — is innate, present even in the wise.", commentary: "Abhiniveśa is the instinctive will to live and fear of death. It runs in its own current (sva-rasa-vāhī), persisting even in those who intellectually know the Self." },
  { id: "2.10", number: 10, pada: 2, sanskrit: "ते प्रतिप्रसवहेयाः सूक्ष्माः", transliteration: "te pratiprasava-heyāḥ sūkṣmāḥ", english: "These subtle kleśas are to be dissolved by tracing them back to their original cause.", commentary: "The subtle forms of the kleśas (in their dormant state) are overcome by pratiprasava — a process of reverse evolution, resolving effects back into their causes." },
  { id: "2.11", number: 11, pada: 2, sanskrit: "ध्यानहेयास्तद्वृत्तयः", transliteration: "dhyāna-heyās tad-vṛttayaḥ", english: "The active modifications of the kleśas are to be subdued through meditation.", commentary: "When the kleśas are active (udāra), they must be countered through dhyāna (meditation) — sustained, focused attention that weakens their hold." },
  { id: "2.12", number: 12, pada: 2, sanskrit: "क्लेशमूलः कर्माशयो दृष्टादृष्टजन्मवेदनीयः", transliteration: "kleśa-mūlaḥ karmāśayo dṛṣṭā-dṛṣṭa-janma-vedanīyaḥ", english: "The accumulated latent impressions of karma, rooted in the kleśas, are experienced in this or a future life.", commentary: "Karmāśaya (the storehouse of karmic impressions) has its root in the kleśas. These karmas will bear fruit either in the present life or in future births." },
  { id: "2.13", number: 13, pada: 2, sanskrit: "सति मूले तद्विपाको जात्यायुर्भोगाः", transliteration: "sati mūle tad-vipāko jāty-āyur-bhogāḥ", english: "As long as the root (of kleśas) exists, its fruition results in birth, lifespan, and the experiences of life.", commentary: "The three fruits of karma are: jāti (type of birth), āyuḥ (lifespan), and bhoga (quality of experiences). These are determined by the accumulated karmas." },
  { id: "2.14", number: 14, pada: 2, sanskrit: "ते ह्लादपरितापफलाः पुण्यापुण्यहेतुत्वात्", transliteration: "te hlāda-paritāpa-phalāḥ puṇya-apuṇya-hetutvāt", english: "These experiences are pleasant or painful according to whether their cause is virtuous or non-virtuous.", commentary: "The fruits (phala) of karma are: hlāda (pleasure) from puṇya (virtuous actions) and paritāpa (pain) from apuṇya (unvirtuous actions)." },
  { id: "2.15", number: 15, pada: 2, sanskrit: "परिणामतापसंस्कारदुःखैर्गुणवृत्तिविरोधाच्च दुःखमेव सर्वं विवेकिनः", transliteration: "pariṇāma-tāpa-saṃskāra-duḥkhair guṇa-vṛtti-virodhāc ca duḥkham eva sarvaṁ vivekinaḥ", english: "To the one with discrimination, everything is suffering — due to the pain of change, anxiety, and latent impressions, as well as the conflicts caused by the interplay of the guṇas.", commentary: "The wise person sees that even seemingly pleasant experiences contain suffering: the suffering of change (pariṇāma), of anxiety (tāpa), of residual impressions (saṃskāra), and of the inherent conflict of the guṇas." },
  { id: "2.16", number: 16, pada: 2, sanskrit: "हेयं दुःखमनागतम्", transliteration: "heyaṁ duḥkham anāgatam", english: "The suffering that has not yet come is to be avoided.", commentary: "Future suffering — suffering that has not yet manifested — can be prevented through the practice of Yoga. This is the practical aim of the path." },
  { id: "2.17", number: 17, pada: 2, sanskrit: "द्रष्टृदृश्ययोः संयोगो हेयहेतुः", transliteration: "draṣṭṛ-dṛśyayoḥ saṃyogo heya-hetuḥ", english: "The cause of that avoidable suffering is the conjunction (saṃyoga) of the Seer (draṣṭṛ) and the Seen (dṛśya).", commentary: "Suffering arises from the misidentification of Puruṣa (Seer) with Prakṛti (Seen). Their conjunction is the root of bondage." },
  { id: "2.18", number: 18, pada: 2, sanskrit: "प्रकाशक्रियास्थितिशीलं भूतेन्द्रियात्मकं भोगापवर्गार्थं दृश्यम्", transliteration: "prakāśa-kriyā-sthiti-śīlaṁ bhūtendriyātmakaṁ bhogāpavargārthaṁ dṛśyam", english: "The Seen (dṛśya) consists of the elements and sense organs, characterized by luminosity, activity, and inertia (sattva, rajas, tamas). Its purpose is both experience (bhoga) and liberation (apavarga) for the Seer.", commentary: "Prakṛti has three guṇas: sattva (prakāśa — light/balance), rajas (kriyā — activity), and tamas (sthiti — inertia). The world exists to provide both experience and liberation to the Puruṣa." },
  { id: "2.19", number: 19, pada: 2, sanskrit: "विशेषाविशेषलिङ्गमात्रालिङ्गानि गुणपर्वाणि", transliteration: "viśeṣā-viśeṣa-liṅga-mātrāliṅgāni guṇa-parvāṇi", english: "The stages of the guṇas are fourfold: specific (viśeṣa), non-specific (aviśeṣa), characterized (liṅga-mātra), and uncharacterized (aliṅga).", commentary: "This describes the hierarchy of Prakṛti's manifestation: from the gross elements (viśeṣa), to the subtle elements (aviśeṣa), to the sense of individuality (liṅga-mātra), to the unmanifest Prakṛti itself (aliṅga)." },
  { id: "2.20", number: 20, pada: 2, sanskrit: "द्रष्टा दृशिमात्रः शुद्धोऽपि प्रत्ययानुपश्यः", transliteration: "draṣṭā dṛśi-mātraḥ śuddho 'pi pratyayānupaśyaḥ", english: "The Seer (Puruṣa) is pure consciousness alone. Though pure, it appears to see through the mind's modifications.", commentary: "The Puruṣa is only and always pure seeing (dṛśi-mātra). However, due to the conjunction with the mind, it appears to take on the coloring of mental activities." },
  { id: "2.21", number: 21, pada: 2, sanskrit: "तदर्थ एव दृश्यस्यात्मा", transliteration: "tad-artha eva dṛśyasyātmā", english: "The very essence of the Seen is for the sake of the Seer.", commentary: "The entire manifested world exists solely for the purpose of the Puruṣa — to provide it with experience and ultimately, liberation." },
  { id: "2.22", number: 22, pada: 2, sanskrit: "कृतार्थं प्रति नष्टमप्यनष्टं तदन्यसाधारणत्वात्", transliteration: "kṛtārthaṁ prati naṣṭam apy anaṣṭaṁ tad-anya-sādhāraṇatvāt", english: "Though the Seen ceases to exist for the one who has attained liberation, it continues to exist for others who are still bound.", commentary: "When a yogi is liberated, Prakṛti's purpose for that individual is fulfilled. But the world continues for others who are still on the path." },
  { id: "2.23", number: 23, pada: 2, sanskrit: "स्वस्वामिशक्त्योः स्वरूपोपलब्धिहेतुः संयोगः", transliteration: "sva-svāmi-śaktyoḥ sva-rūpopalabdhi-hetuḥ saṃyogaḥ", english: "The conjunction (saṃyoga) between the owner (Puruṣa) and the owned (Prakṛti) allows for the recognition of their true natures.", commentary: "The purpose of the conjunction is not ultimately suffering but the realization (upalabdhi) of the distinction between Puruṣa and Prakṛti." },
  { id: "2.24", number: 24, pada: 2, sanskrit: "तस्य हेतुरविद्या", transliteration: "tasya hetur avidyā", english: "Ignorance (avidyā) is the cause of this conjunction.", commentary: "The conjunction of Seer and Seen is rooted in avidyā — the primordial misapprehension of reality. Remove avidyā, and the conjunction dissolves." },
  { id: "2.25", number: 25, pada: 2, sanskrit: "तदभावात्संयोगाभावो हानं तद्दृशेः कैवल्यम्", transliteration: "tad-abhāvāt saṃyogābhāvo hānaṁ tad dṛśeḥ kaivalyam", english: "When ignorance is removed, the conjunction ceases. This cessation, the independence of the Seer, is liberation (kaivalya).", commentary: "Kaivalya (liberation) is the state of the Seer's absolute independence, achieved when avidyā and the subsequent conjunction with Prakṛti are completely removed." },
  { id: "2.26", number: 26, pada: 2, sanskrit: "विवेकख्यातिरविप्लवा हानोपायः", transliteration: "viveka-khyātir aviplavā hāna-upāyaḥ", english: "The uninterrupted practice of discriminative discernment (viveka-khyāti) is the means of liberation.", commentary: "The method to eliminate avidyā is viveka-khyāti — the continuous, unwavering discernment between the true Self (Puruṣa) and the not-Self (Prakṛti)." },
  { id: "2.27", number: 27, pada: 2, sanskrit: "तस्य सप्तधा प्रान्तभूमिः प्रज्ञा", transliteration: "tasya saptadhā prānta-bhūmiḥ prajñā", english: "Supreme wisdom (prajñā) in the final stage consists of seven levels.", commentary: "As viveka-khyāti deepens, wisdom unfolds in seven stages, each bringing the yogi closer to complete liberation." },
  { id: "2.28", number: 28, pada: 2, sanskrit: "योगाङ्गानुष्ठानादशुद्धिक्षये ज्ञानदीप्तिरा विवेकख्यातेः", transliteration: "yogāṅgānuṣṭhānād aśuddhi-kṣaye jñāna-dīptir ā viveka-khyāteḥ", english: "Through the practice of the limbs of yoga (yogāṅga), as impurity diminishes, the light of knowledge grows, culminating in discriminative wisdom.", commentary: "The systematic practice of the eight limbs of Yoga purifies the mind, leading to the radiant light of discriminative knowledge." },
  { id: "2.29", number: 29, pada: 2, sanskrit: "यमनियमासनप्राणायामप्रत्याहारधारणाध्यानसमाधयोऽष्टावङ्गानि", transliteration: "yama-niyamāsana-prāṇāyāma-pratyāhāra-dhāraṇā-dhyāna-samādhayo 'ṣṭāv aṅgāni", english: "The eight limbs of yoga are: moral restraints (yama), observances (niyama), posture (āsana), breath control (prāṇāyāma), sense withdrawal (pratyāhāra), concentration (dhāraṇā), meditation (dhyāna), and complete absorption (samādhi).", commentary: "This is the famous aṣṭāṅga (eight-limbed) path of Classical Yoga. The first five are external aids (bahiraṅga), the last three are internal (antaraṅga)." },
  { id: "2.30", number: 30, pada: 2, sanskrit: "अहिंसासत्यास्तेयब्रह्मचर्यापरिग्रहा यमाः", transliteration: "ahiṁsā-satyāsteya-brahmacaryāparigrahā yamāḥ", english: "The five yamas (restraints) are: non-violence (ahiṁsā), truthfulness (satya), non-stealing (asteya), celibacy/chastity (brahmacarya), and non-possessiveness (aparigraha).", commentary: "Yamas are universal ethical principles that form the foundation of yogic life." },
  { id: "2.31", number: 31, pada: 2, sanskrit: "जातिदेशकालसमयानवच्छिन्नाः सार्वभौमा महाव्रतम्", transliteration: "jāti-deśa-kāla-samayānavacchinnāḥ sārvabhaumā mahā-vratam", english: "These yamas, unrestricted by class, place, time, or circumstance, are universal great vows.", commentary: "The yamas are absolute and universal — they apply to all beings, at all times, in all circumstances. They are not conditional." },
  { id: "2.32", number: 32, pada: 2, sanskrit: "शौचसंतोषतपःस्वाध्यायेश्वरप्रणिधानानि नियमाः", transliteration: "śauca-saṃtoṣa-tapaḥ-svādhyāyeśvara-praṇidhānāni niyamāḥ", english: "The five niyamas (observances) are: purity (śauca), contentment (saṃtoṣa), austerity (tapas), self-study (svādhyāya), and devotion to the Lord (īśvara-praṇidhāna).", commentary: "Niyamas are personal observances that cultivate inner discipline and spiritual growth." },
  { id: "2.33", number: 33, pada: 2, sanskrit: "वितर्कबाधने प्रतिपक्षभावनम्", transliteration: "vitarka-bādhane pratipakṣa-bhāvanam", english: "When disturbed by negative thoughts, meditation on the opposite (positive) thoughts should be practiced.", commentary: "Pratipakṣa-bhāvanā is the practice of actively cultivating the opposite mental state to counteract negative or harmful tendencies." },
  { id: "2.34", number: 34, pada: 2, sanskrit: "वितर्का हिंसादयः कृतकारितानुमोदिता लोभक्रोधमोहपूर्वका मृदुमध्याधिमात्रा दुःखाज्ञानानन्तफला इति प्रतिपक्षभावनम्", transliteration: "vitarkā hiṁsādayaḥ kṛta-kāritānumoditā lobha-krodha-moha-pūrvakā mṛdu-madhyādhimātrā duḥkhājñānānanta-phalā iti pratipakṣa-bhāvanam", english: "Negative thoughts such as violence, whether done, caused to be done, or approved of — whether arising from greed, anger, or delusion — and whether mild, moderate, or intense — result in infinite suffering and ignorance. Therefore, cultivate the opposite.", commentary: "Patañjali emphasizes that even indirect participation in harmful acts (by causing or approving) creates karma. The antidote is pratipakṣa-bhāvanā — consciously cultivating the opposite virtue." },
  { id: "2.35", number: 35, pada: 2, sanskrit: "अहिंसाप्रतिष्ठायां तत्सन्निधौ वैरत्यागः", transliteration: "ahiṁsā-pratiṣṭhāyāṁ tat-sannidhau vairatyāgaḥ", english: "When non-violence (ahiṁsā) is established, hostility ceases in one's presence.", commentary: "The perfection of ahiṁsā creates an aura of peace — even natural enemies become peaceful in the presence of such a yogi." },
  { id: "2.36", number: 36, pada: 2, sanskrit: "सत्यप्रतिष्ठायां क्रियाफलाश्रयत्वम्", transliteration: "satya-pratiṣṭhāyāṁ kriyā-phalāśrayatvam", english: "When truthfulness (satya) is established, actions and their results depend on the yogi.", commentary: "The perfected yogi of truth speaks and acts with such power that whatever they say or intend comes to pass." },
  { id: "2.37", number: 37, pada: 2, sanskrit: "अस्तेयप्रतिष्ठायां सर्वरत्नोपस्थानम्", transliteration: "asteya-pratiṣṭhāyāṁ sarva-ratnopasthānam", english: "When non-stealing (asteya) is established, all jewels and treasures present themselves.", commentary: "The perfected yogi who does not covet finds that all wealth comes naturally, without any effort to acquire it." },
  { id: "2.38", number: 38, pada: 2, sanskrit: "ब्रह्मचर्यप्रतिष्ठायां वीर्यलाभः", transliteration: "brahmacarya-pratiṣṭhāyāṁ vīrya-lābhaḥ", english: "When celibacy/chastity (brahmacarya) is established, vigor and spiritual energy are attained.", commentary: "Brahmacarya (abiding in the Supreme Reality) conserves vital energy, resulting in vīrya — immense vitality, courage, and spiritual strength." },
  { id: "2.39", number: 39, pada: 2, sanskrit: "अपरिग्रहस्थैर्ये जन्मकथन्तासम्बोधः", transliteration: "aparigraha-sthairye janma-kathantā-sambodhaḥ", english: "When non-possessiveness (aparigraha) is firmly established, knowledge of past and future lives arises.", commentary: "Free from hoarding and grasping, the mind becomes clear enough to perceive the nature of rebirth and the cycle of existence." },
  { id: "2.40", number: 40, pada: 2, sanskrit: "शौचात्स्वाङ्गजुगुप्सा परैरसंसर्गः", transliteration: "śaucāt svāṅga-jugupsā parair asaṃsargaḥ", english: "From purity (śauca), there arises a disinterest in one's own body and a cessation of contact with others.", commentary: "External purity leads to detachment from the physical body and its limitations." },
  { id: "2.41", number: 41, pada: 2, sanskrit: "सत्त्वशुद्धिसौमनस्यैकाग्र्येन्द्रियजयात्मदर्शनयोग्यत्वानि च", transliteration: "sattva-śuddhi-saumanasyaikāgryendriya-jayātma-darśana-yogyatvāni ca", english: "From internal purity come clarity of mind, cheerfulness, one-pointedness, mastery of the senses, and fitness for self-realization.", commentary: "Inner purification (śauca) of the mind yields sattva-śuddhi (purity of the mental substance), leading to fitness for direct Self-knowledge." },
  { id: "2.42", number: 42, pada: 2, sanskrit: "संतोषादनुत्तमः सुखलाभः", transliteration: "saṃtoṣād anuttamaḥ sukha-lābhaḥ", english: "From contentment (saṃtoṣa), supreme happiness is attained.", commentary: "Contentment is the key to happiness not dependent on external conditions. The yogi who is content with whatever comes experiences unsurpassed bliss." },
  { id: "2.43", number: 43, pada: 2, sanskrit: "कायेन्द्रियसिद्धिरशुद्धिक्षयात्तपसः", transliteration: "kāyendriya-siddhir aśuddhi-kṣayāt tapasaḥ", english: "Through austerity (tapas), impurities are destroyed, and the body and senses attain perfection.", commentary: "Tapas (disciplined practice, often involving physical austerity) purifies the body and senses, leading to extraordinary capabilities (siddhi)." },
  { id: "2.44", number: 44, pada: 2, sanskrit: "स्वाध्यायादिष्टदेवतासम्प्रयोगः", transliteration: "svādhyāyād iṣṭa-devatā-samprayogaḥ", english: "Through self-study (svādhyāya), communion with the chosen deity is attained.", commentary: "Svādhyāya — the study of spiritual scriptures and self-reflection — leads to connection with the divine aspect one reveres." },
  { id: "2.45", number: 45, pada: 2, sanskrit: "समाधिसिद्धिरीश्वरप्रणिधानात्", transliteration: "samādhi-siddhir īśvara-praṇidhānāt", english: "Through devotion to the Lord (īśvara-praṇidhāna), the perfection of samādhi is attained.", commentary: "Complete surrender to Īśvara directly leads to the highest goal — the perfection of samādhi and liberation." },
  { id: "2.46", number: 46, pada: 2, sanskrit: "स्थिरसुखमासनम्", transliteration: "sthira-sukham āsanam", english: "Posture (āsana) should be steady and comfortable.", commentary: "Āsana is the third limb. The key qualities are sthira (steadiness/firmness) and sukha (ease/comfort). The body should be stable and relaxed, neither tense nor limp." },
  { id: "2.47", number: 47, pada: 2, sanskrit: "प्रयत्नशैथिल्यानन्तसमापत्तिभ्याम्", transliteration: "prayatna-śaithilyānanta-samāpattibhyām", english: "Āsana is perfected through relaxation of effort and meditation on the infinite.", commentary: "Two methods: (1) prayatna-śaithilya — releasing all physical effort/ tension, and (2) ananta-samāpatti — contemplating the infinite, which dissolves bodily awareness." },
  { id: "2.48", number: 48, pada: 2, sanskrit: "ततो द्वन्द्वानभिघातः", transliteration: "tato dvandvānabhighātaḥ", english: "From that, one is not afflicted by the pairs of opposites.", commentary: "When āsana is perfected, the yogi transcends the dualities of physical existence: heat/cold, pleasure/pain, etc." },
  { id: "2.49", number: 49, pada: 2, sanskrit: "तस्मिन्सति श्वासप्रश्वासयोर्गतिविच्छेदः प्राणायामः", transliteration: "tasmin sati śvāsa-praśvāsayo gati-vicchedaḥ prāṇāyāmaḥ", english: "When that (āsana) is accomplished, prāṇāyāma — the regulation of the movements of inhalation and exhalation — follows.", commentary: "Prāṇāyāma (breath control) is the fourth limb. Once the body is steady, the yogi turns to controlling the breath, the link between body and mind." },
  { id: "2.50", number: 50, pada: 2, sanskrit: "बाह्याभ्यन्तरस्तम्भवृत्तिर्देशकालसङ्ख्याभिः परिदृष्टो दीर्घसूक्ष्मः", transliteration: "bāhyābhyantara-stambha-vṛttir deśa-kāla-saṅkhyābhiḥ paridṛṣṭo dīrgha-sūkṣmaḥ", english: "Prāṇāyāma has three movements: external (exhalation), internal (inhalation), and suspension. These are regulated by place, time, and number, becoming prolonged and subtle.", commentary: "Prāṇāyāma involves three phases: recaka (exhalation), pūraka (inhalation), and kumbhaka (retention). Practice refines these through spatial, temporal, and numerical control." },
  { id: "2.51", number: 51, pada: 2, sanskrit: "बाह्याभ्यन्तरविषयाक्षेपी चतुर्थः", transliteration: "bāhyābhyantara-viṣayākṣepī caturthaḥ", english: "The fourth type of prāṇāyāma transcends the domains of internal and external.", commentary: "Beyond inhalation, exhalation, and retention is a fourth, transcendent prāṇāyāma — the natural suspension of breath that occurs in deep meditation." },
  { id: "2.52", number: 52, pada: 2, sanskrit: "ततः क्षीयते प्रकाशावरणम्", transliteration: "tataḥ kṣīyate prakāśāvaraṇam", english: "From that (prāṇāyāma), the veil of karmic obscurations covering the light of knowledge is thinned.", commentary: "Prāṇāyāma removes the āvaraṇa (veil) that covers the inner light (prakāśa) of discrimination." },
  { id: "2.53", number: 53, pada: 2, sanskrit: "धारणासु च योग्यता मनसः", transliteration: "dhāraṇāsu ca yogyatā manasaḥ", english: "And the mind becomes fit for concentration (dhāraṇā).", commentary: "Prāṇāyāma prepares the mind for the deeper, internal limbs of Yoga — dhāraṇā, dhyāna, and samādhi." },
  { id: "2.54", number: 54, pada: 2, sanskrit: "स्वविषयासम्प्रयोगे चित्तस्वरूपानुकार इवेन्द्रियाणां प्रत्याहारः", transliteration: "sva-viṣayāsamprayoge cittasya svarūpānukāra ivendriyāṇāṁ pratyāhāraḥ", english: "Pratyāhāra (sense withdrawal) occurs when the senses cease to engage with their objects, and instead follow the nature of the mind.", commentary: "Pratyāhāra is the fifth limb. The senses, instead of reaching outward to their objects, are drawn inward, imitating the withdrawn state of the mind." },
  { id: "2.55", number: 55, pada: 2, sanskrit: "ततः परमा वश्यतेन्द्रियाणाम्", transliteration: "tataḥ paramā vaśyatendriyāṇām", english: "From that, there arises the supreme mastery of the senses.", commentary: "When pratyāhāra is perfected, the yogi attains complete control over the senses — they no longer disrupt the mind's focus." },
]

// ── Pada 3: Vibhuti Pada (55-56 sutras) ──────────────────────────────
const vibhutiPadaVerses: YogaSutraVerse[] = [
  { id: "3.1", number: 1, pada: 3, sanskrit: "देशबन्धश्चित्तस्य धारणा", transliteration: "deśa-bandhaś cittasya dhāraṇā", english: "Concentration (dhāraṇā) is the binding of the mind to a single place, object, or region.", commentary: "Dhāraṇā, the sixth limb, is the first of the internal limbs (antaraṅga). It is focused attention directed at a specific point." },
  { id: "3.2", number: 2, pada: 3, sanskrit: "तत्र प्रत्ययैकतानता ध्यानम्", transliteration: "tatra pratyayaikatānatā dhyānam", english: "Meditation (dhyāna) is the uninterrupted flow of attention toward that object.", commentary: "Dhyāna is the seventh limb — when the mind's focus flows continuously toward the chosen object without interruption, like the steady flow of oil." },
  { id: "3.3", number: 3, pada: 3, sanskrit: "तदेवार्थमात्रनिर्भासं स्वरूपशून्यमिव समाधिः", transliteration: "tad evārtha-mātra-nirbhāsaṁ svarūpa-śūnyam iva samādhiḥ", english: "That same meditation, when only the object shines forth and the mind's own nature appears absent, is samādhi (complete absorption).", commentary: "Samādhi is the eighth limb — the culmination where the mind loses itself in the object, and only the object's presence remains." },
  { id: "3.4", number: 4, pada: 3, sanskrit: "त्रयमेकत्र संयमः", transliteration: "trayam ekatra saṃyamaḥ", english: "These three together (dhāraṇā, dhyāna, samādhi) constitute saṃyama (perfect discipline).", commentary: "Saṃyama is the unified practice of the last three limbs applied to a single object. This is the key to attaining yogic powers (vibhūtis)." },
  { id: "3.5", number: 5, pada: 3, sanskrit: "तज्जयात्प्रज्ञालोकः", transliteration: "taj-jayāt prajñālokaḥ", english: "By mastering saṃyama, the light of supreme wisdom dawns.", commentary: "When saṃyama is perfected, prajñā (wisdom) illuminates the true nature of the object under contemplation." },
  { id: "3.6", number: 6, pada: 3, sanskrit: "तस्य भूमिषु विनियोगः", transliteration: "tasya bhūmiṣu viniyogaḥ", english: "Its application is gradual, stage by stage.", commentary: "The practice of saṃyama proceeds through progressive stages (bhūmis), each leading deeper into realization." },
  { id: "3.7", number: 7, pada: 3, sanskrit: "त्रयमन्तरङ्गं पूर्वेभ्यः", transliteration: "trayam antaraṅgaṁ pūrvebhyaḥ", english: "These three (dhāraṇā, dhyāna, samādhi) are more internal than the preceding five limbs.", commentary: "The last three limbs are antaraṅga (internal) compared to the first five (yama, niyama, āsana, prāṇāyāma, pratyāhāra) which are bahiraṅga (external)." },
  { id: "3.8", number: 8, pada: 3, sanskrit: "तदपि बहिरङ्गं निर्बीजस्य", transliteration: "tad api bahiraṅgaṁ nirbījasya", english: "Yet even these three are external to seedless (nirbīja) samādhi.", commentary: "Even saṃyama is considered external when compared to the ultimate state of seedless samādhi, where no object remains." },
  { id: "3.9", number: 9, pada: 3, sanskrit: "व्युत्थाननिरोधसंस्कारयोरभिभवप्रादुर्भावौ निरोधक्षणचित्तान्वयो निरोधपरिणामः", transliteration: "vyutthāna-nirodha-saṃskārayor abhibhava-prādurbhāvau nirodha-kṣaṇa-cittānvayo nirodha-pariṇāmaḥ", english: "The transformation of restraint (nirodha-pariṇāma) occurs when the mind moves between manifest and restrained states, with the impressions of restraint gradually dominating.", commentary: "This describes the subtle process of mental transformation as the yogi moves from distraction (vyutthāna) to restraint (nirodha)." },
  { id: "3.10", number: 10, pada: 3, sanskrit: "तस्य प्रशान्तवाहिता संस्कारात्", transliteration: "tasya praśānta-vāhitā saṃskārāt", english: "From that, the mind flows in tranquility, sustained by repeated practice.", commentary: "When nirodha-pariṇāma is established, the mind's flow becomes peaceful and steady — a natural state of calm." },
  { id: "3.11", number: 11, pada: 3, sanskrit: "सर्वार्थतैकाग्रतयोः क्षयोदयौ चित्तस्य समाधिपरिणामः", transliteration: "sarvārthataikāgratayoḥ kṣayodayau cittasya samādhi-pariṇāmaḥ", english: "The transformation toward samādhi (samādhi-pariṇāma) is the weakening of distraction and the simultaneous arising of one-pointedness.", commentary: "As one-pointedness increases, the mind's tendency to be scattered (sarvārthatā) diminishes." },
  { id: "3.12", number: 12, pada: 3, sanskrit: "ततः पुनः शान्तोदितौ तुल्यप्रत्ययौ चित्तस्यैकाग्रतापरिणामः", transliteration: "tataḥ punaḥ śāntoditau tulya-pratyayau cittasyaikāgratā-pariṇāmaḥ", english: "Then the state of one-pointedness (ekāgratā-pariṇāma) occurs — when both the subsiding and arising thought-activity are equal in nature.", commentary: "In this state, past and present mental activities become similar in quality, indicating mind's stability." },
  { id: "3.13", number: 13, pada: 3, sanskrit: "एतेन भूतेन्द्रियेषु धर्मलक्षणावस्थापरिणामा व्याख्याताः", transliteration: "etena bhūtendriyeṣu dharma-lakṣaṇāvasthā-pariṇāmā vyākhyātāḥ", english: "Through these principles, the three transformations in the elements and senses — of dharma (characteristic), lakṣaṇa (time-phase), and avasthā (state) — are explained.", commentary: "Everything in nature undergoes three types of change: intrinsic nature (dharma), temporal condition (lakṣaṇa), and present state (avasthā)." },
  { id: "3.14", number: 14, pada: 3, sanskrit: "शान्तोदिताव्यपदेश्यधर्मानुपाती धर्मी", transliteration: "śāntoditāvyapadeśya-dharmānupātī dharmī", english: "The substrate (dharmī) is that which undergoes the sequence of quiescent, active, and unmanifest characteristics.", commentary: "All objects possess characteristics that can be latent (śānta), manifest (udita), or unmanifest (avyapadeśya). The underlying substance (dharmī) persists through these changes." },
  { id: "3.15", number: 15, pada: 3, sanskrit: "क्रमान्यत्वं परिणामान्यत्वे हेतुः", transliteration: "kramānyatvaṁ pariṇāmānyatve hetuḥ", english: "The difference in sequence (krama) is the cause of the difference in transformation.", commentary: "The order or sequence in which changes occur determines the nature of the transformation." },
  { id: "3.16", number: 16, pada: 3, sanskrit: "परिणामत्रयसंयमादतीतानागतज्ञानम्", transliteration: "pariṇāma-traya-saṃyamād atītānāgata-jñānam", english: "By practicing saṃyama on the three transformations, knowledge of the past and future arises.", commentary: "When the yogi understands the three forms of transformation, they can perceive the past and future." },
  { id: "3.17", number: 17, pada: 3, sanskrit: "शब्दार्थप्रत्ययानामितरेतराध्यासात्सङ्करस्तत्प्रविभागसंयमात्सर्वभूतरुतज्ञानम्", transliteration: "śabdārtha-pratyayānām itaretarādhyāsāt saṅkaras tat-pravibhāga-saṃyamāt sarva-bhūta-ruta-jñānam", english: "Word (śabda), meaning (artha), and idea (pratyaya) are mixed together. By saṃyama on their distinctions, one understands the sounds of all beings.", commentary: "This sutra explains how language works and how saṃyama on the distinction between word, object, and mental concept can give knowledge of all sounds." },
  { id: "3.18", number: 18, pada: 3, sanskrit: "संस्कारसाक्षात्करणात्पूर्वजातिज्ञानम्", transliteration: "saṃskāra-sākṣāt-karaṇāt pūrva-jāti-jñānam", english: "By direct perception of latent impressions (saṃskāras), knowledge of past lives arises.", commentary: "Saṃyama on one's own or others' saṃskāras reveals the experiences that created them, giving knowledge of past lives." },
  { id: "3.19", number: 19, pada: 3, sanskrit: "प्रत्ययस्य परचित्तज्ञानम्", transliteration: "pratyayasya para-citta-jñānam", english: "By saṃyama on mental images (pratyaya), knowledge of other minds arises.", commentary: "The yogi can perceive the content of another person's mind by focusing on the mental images within their own." },
  { id: "3.20", number: 20, pada: 3, sanskrit: "न च तत्सालम्बनं तस्याविषयीभूतत्वात्", transliteration: "na ca tat sālambanaṁ tasyāviṣayībhūtatvāt", english: "But not the underlying support (ālambana) of that mental content — because that is beyond the scope of direct perception.", commentary: "One can know another's thoughts but not the underlying reality or the context of those thoughts." },
  { id: "3.21", number: 21, pada: 3, sanskrit: "कायरूपसंयमात्तद्ग्राह्यशक्तिस्तम्भे चक्षुःप्रकाशासम्प्रयोगेऽन्तर्धानम्", transliteration: "kāya-rūpa-saṃyamāt tad-grāhya-śakti-stambhe cakṣuḥ-prakāśā-samprayoge 'ntardhānam", english: "By saṃyama on the form of the body, when the power of being perceived is suspended and the light of the eyes is withdrawn, the body becomes invisible.", commentary: "The yogi can become invisible by disrupting the mechanism through which others perceive their body." },
  { id: "3.22", number: 22, pada: 3, sanskrit: "एतेन शब्दाद्यन्तर्धानमुक्तम्", transliteration: "etena śabdādy antardhānam uktam", english: "By the same principle, the invisibility of sound and other sense objects is explained.", commentary: "Just as visibility can be suspended, so can audibility and other sense-perceptible qualities." },
  { id: "3.23", number: 23, pada: 3, sanskrit: "सोपक्रमं निरुपक्रमं च कर्म तत्संयमादपरान्तज्ञानमरिष्टेभ्यो वा", transliteration: "sopakramaṁ nirupakramaṁ ca karma tat-saṃyamād aparānta-jñānam ariṣṭebhyo vā", english: "Karma may be quick or slow in manifesting. By saṃyama on karma, or from the signs of approaching death, knowledge of the end of life arises.", commentary: "The yogi can know the time of death by analyzing the nature of accumulated karma or by perceiving omens (ariṣṭa)." },
  { id: "3.24", number: 24, pada: 3, sanskrit: "मैत्र्यादिषु बलानि", transliteration: "maitryādiṣu balāni", english: "By saṃyama on friendliness (maitrī) and other attitudes, one acquires their respective powers.", commentary: "Focusing on the qualities of friendliness, compassion, and joy through saṃyama causes these qualities to develop into powerful capacities." },
  { id: "3.25", number: 25, pada: 3, sanskrit: "बलेषु हस्तिबलादीनि", transliteration: "baleṣu hasti-balādīni", english: "By saṃyama on powers, one attains the strength of an elephant, etc.", commentary: "Contemplating the nature of specific strengths allows the yogi to embody them." },
  { id: "3.26", number: 26, pada: 3, sanskrit: "प्रवृत्त्यालोकन्यासात्सूक्ष्मव्यवहितविप्रकृष्टज्ञानम्", transliteration: "pravṛtty-āloka-nyāsāt sūkṣma-vyavahita-viprakṛṣṭa-jñānam", english: "By directing the inner light (pravṛtti-āloka) through saṃyama, knowledge of the subtle, hidden, and distant arises.", commentary: "The yogi can perceive subtle, concealed, or distant objects by projecting the inner light of consciousness upon them." },
  { id: "3.27", number: 27, pada: 3, sanskrit: "भुवनज्ञानं सूर्ये संयमात्", transliteration: "bhuvana-jñānaṁ sūrye saṃyamāt", english: "By saṃyama on the sun, knowledge of the entire solar system arises.", commentary: "Contemplating the sun reveals cosmic knowledge about the universe." },
  { id: "3.28", number: 28, pada: 3, sanskrit: "चन्द्रे ताराव्यूहज्ञानम्", transliteration: "candre tārā-vyūha-jñānam", english: "By saṃyama on the moon, knowledge of the arrangement of the stars arises.", commentary: "This sutra extends the principle — saṃyama on celestial bodies reveals astronomical knowledge." },
  { id: "3.29", number: 29, pada: 3, sanskrit: "ध्रुवे तद्गतिज्ञानम्", transliteration: "dhruve tad-gati-jñānam", english: "By saṃyama on the polestar, knowledge of the motion of the stars arises.", commentary: "Understanding the fixed polestar reveals knowledge of stellar movement." },
  { id: "3.30", number: 30, pada: 3, sanskrit: "नाभिचक्रे कायव्यूहज्ञानम्", transliteration: "nābhi-cakre kāya-vyūha-jñānam", english: "By saṃyama on the navel cakra, knowledge of the constitution of the body arises.", commentary: "Focusing on the navel region reveals detailed understanding of the body's structure and systems." },
  { id: "3.31", number: 31, pada: 3, sanskrit: "कण्ठकूपे क्षुत्पिपासानिवृत्तिः", transliteration: "kaṇṭha-kūpe kṣut-pipāsā-nivṛttiḥ", english: "By saṃyama on the throat-cavity, cessation of hunger and thirst occurs.", commentary: "The yogi can overcome bodily urges through focused awareness on the throat region." },
  { id: "3.32", number: 32, pada: 3, sanskrit: "कूर्मनाड्यां स्थैर्यम्", transliteration: "kūrma-nāḍyāṁ sthairyam", english: "By saṃyama on the 'tortoise-channel' (a subtle nerve), steadiness of the body and mind is attained.", commentary: "Focusing on this subtle channel brings profound stability." },
  { id: "3.33", number: 33, pada: 3, sanskrit: "मूर्धज्योतिषि सिद्धदर्शनम्", transliteration: "mūrdha-jyotiṣi siddha-darśanam", english: "By saṃyama on the light at the crown of the head, one sees perfected beings (siddhas).", commentary: "Directing awareness to the crown allows vision of enlightened masters." },
  { id: "3.34", number: 34, pada: 3, sanskrit: "प्रातिभाद्वा सर्वम्", transliteration: "prātibhād vā sarvam", english: "Or, all these powers arise spontaneously through intuitive illumination (prātibha).", commentary: "Some powers arise naturally through the spontaneous awakening of intuition, without deliberate practice." },
  { id: "3.35", number: 35, pada: 3, sanskrit: "हृदये चित्तसंवित्", transliteration: "hṛdaye citta-saṃvit", english: "By saṃyama on the heart, knowledge of the nature of mind (citta) arises.", commentary: "Focusing on the heart center reveals the workings of consciousness itself." },
  { id: "3.36", number: 36, pada: 3, sanskrit: "सत्त्वपुरुषयोरत्यन्तासंकीर्णयोः प्रत्ययाविशेषो भोगः परार्थत्वात्स्वार्थसंयमात्पुरुषज्ञानम्", transliteration: "sattva-puruṣayor atyantāsaṅkīrṇayoḥ pratyayāviśeṣo bhogaḥ parārthatvāt svārtha-saṃyamāt puruṣa-jñānam", english: "Experience (bhoga) arises from the failure to distinguish between sattva (pure intellect) and Puruṣa (pure consciousness). By saṃyama on the distinction between the two, knowledge of Puruṣa arises.", commentary: "This is a crucial sutra: the distinction between the mind's purest state (sattva) and the true Self (Puruṣa) is the key to liberating knowledge." },
  { id: "3.37", number: 37, pada: 3, sanskrit: "ततः प्रातिभश्रावणवेदनादर्शास्वादवार्ता जायन्ते", transliteration: "tataḥ prātibha-śrāvaṇa-vedanādarśāsvāda-vārtā jāyante", english: "From that arise intuitive, auditory, tactile, visual, gustatory, and olfactory supernormal perceptions.", commentary: "When knowledge of Puruṣa dawns, various psychic perceptions (siddhis) naturally manifest." },
  { id: "3.38", number: 38, pada: 3, sanskrit: "ते समाधावुपसर्गा व्युत्थाने सिद्धयः", transliteration: "te samādhāv upasargā vyutthāne siddhayaḥ", english: "These siddhis are perfections in the worldly state but obstacles to samādhi.", commentary: "This is Patañjali's important warning: psychic powers are attainments (siddhis) for worldly life but obstructions (upasargas) on the path to true samādhi." },
  { id: "3.39", number: 39, pada: 3, sanskrit: "बन्धकारणशैथिल्यात्प्रचारसंवेदनाच्च चित्तस्य परशरीरावेशः", transliteration: "bandha-kāraṇa-śaithilyāt pracāra-saṃvedanāc ca cittasya para-śarīrāveśaḥ", english: "By loosening the causes of bondage and by having knowledge of the channels of the mind, the yogi can enter another's body.", commentary: "The yogi can transfer consciousness into another body by understanding the subtle channels through which the mind operates." },
  { id: "3.40", number: 40, pada: 3, sanskrit: "उदानजयाज्जलपङ्ककण्टकादिष्वसङ्ग उत्क्रान्तिश्च", transliteration: "udāna-jayāj jala-paṅka-kaṇṭakādiṣv asaṅga utkrāntiś ca", english: "By mastering udāna (the upward-moving prāṇa), one can levitate and walk on water, mud, thorns, etc., and attain voluntary death.", commentary: "Mastery of udāna vāyu gives lightness and the ability to leave the body at will." },
  { id: "3.41", number: 41, pada: 3, sanskrit: "समानजयात्प्रज्वलनम्", transliteration: "samāna-jayāt prajvalanam", english: "By mastering samāna (the equalizing prāṇa), the body radiates a brilliant glow.", commentary: "Samāna vāyu, when mastered, creates an inner radiance around the body." },
  { id: "3.42", number: 42, pada: 3, sanskrit: "श्रोत्राकाशयोः सम्बन्धसंयमाद्दिव्यं श्रोत्रम्", transliteration: "śrotrākāśayoḥ sambandha-saṃyamād divyaṁ śrotram", english: "By saṃyama on the relationship between the ear and space (ākāśa), divine hearing arises.", commentary: "The yogi can hear sounds at any distance by understanding space's role in transmitting sound." },
  { id: "3.43", number: 43, pada: 3, sanskrit: "कायाकाशयोः सम्बन्धसंयमाल्लघुतूलसमापत्तेश्चाकाशगमनम्", transliteration: "kāyākāśayoḥ sambandha-saṃyamāl laghu-tūla-samāpatteś cākāśa-gamanam", english: "By saṃyama on the relationship between the body and space, and by cultivating lightness like cotton, the yogi can travel through space.", commentary: "The perfected yogi attains levitation and movement through space." },
  { id: "3.44", number: 44, pada: 3, sanskrit: "बहिरकल्पिता वृत्तिर्महाविदेहा ततः प्रकाशावरणक्षयः", transliteration: "bahir akalpitā vṛttir mahā-videhā tataḥ prakāśāvaraṇa-kṣayaḥ", english: "The state of being without a body (mahā-videhā) — the mind's activity external to the body, without conceptualization — destroys the veil covering the light.", commentary: "The great discarnate state allows the mind to function beyond the body, removing the final veils of ignorance." },
  { id: "3.45", number: 45, pada: 3, sanskrit: "स्थूलस्वरूपसूक्ष्मान्वयार्थवत्त्वसंयमाद्भूतजयः", transliteration: "sthūla-svarūpa-sūkṣmānvayārthavattva-saṃyamād bhūta-jayaḥ", english: "By saṃyama on the gross, essential nature, subtle, and purposeful aspects of the elements, mastery over them is attained.", commentary: "The yogi gains mastery over the five elements by understanding them at all levels — from gross to subtle to their ultimate purpose." },
  { id: "3.46", number: 46, pada: 3, sanskrit: "ततोऽणिमादिप्रादुर्भावः कायसंपत्तद्धर्मानभिघातश्च", transliteration: "tato 'ṇimādi-prādurbhāvaḥ kāya-sampat tad-dharmānabhighātaś ca", english: "From that arise the powers of becoming minute (aṇimā), etc., the perfection of the body, and the inability of the elements to obstruct it.", commentary: "Eight great siddhis (aṣṭa-siddhi) manifest: aṇimā (become minute), mahimā (become vast), laghimā (become light), garimā (become heavy), prāpti (reach anything), prākāmya (achieve anything), īśitva (lordship), and vaśitva (mastery)." },
  { id: "3.47", number: 47, pada: 3, sanskrit: "रूपलावण्यबलवज्रसंहननत्वानि कायसम्पत्", transliteration: "rūpa-lāvaṇya-bala-vajra-saṃhananatvāni kāya-sampat", english: "The perfections of the body include: beauty, grace, strength, and adamantine firmness.", commentary: "When elemental mastery is attained, the physical body becomes perfect in form and indestructible." },
  { id: "3.48", number: 48, pada: 3, sanskrit: "ग्रहणस्वरूपास्मितान्वयार्थवत्त्वसंयमादिन्द्रियजयः", transliteration: "grahaṇa-svarūpāsmitānvayārthavattva-saṃyamād indriya-jayaḥ", english: "By saṃyama on the power of grasping (grahaṇa), its essential nature, ego-sense (asmitā), connectedness, and purpose — mastery of the senses is attained.", commentary: "Mastery over the senses comes from understanding them at all levels — from their function to their ultimate purpose." },
  { id: "3.49", number: 49, pada: 3, sanskrit: "ततो मनोजवित्वं विकरणभावः प्रधानजयश्च", transliteration: "tato mano-javitvaṁ vikaraṇa-bhāvaḥ pradhāna-jayaś ca", english: "From that arise speed of the mind like that of the senses operating independently of the body, and mastery over the primordial cause (prakṛti).", commentary: "The senses function without needing the physical body, and the yogi gains mastery over the entire field of nature (prakṛti)." },
  { id: "3.50", number: 50, pada: 3, sanskrit: "सत्त्वपुरुषान्यताख्यातिमात्रस्य सर्वभावाधिष्ठातृत्वं सर्वज्ञातृत्वं च", transliteration: "sattva-puruṣānyatā-khyāti-mātrasya sarva-bhāvādhiṣṭhātṛtvaṁ sarva-jñātṛtvaṁ ca", english: "To the one who discerns the distinction between sattva and Puruṣa, there comes omniscience and lordship over all states of being.", commentary: "When the final distinction is made — between the pure intellect (sattva) and the true Self (Puruṣa) — the yogi attains supreme knowledge and power." },
  { id: "3.51", number: 51, pada: 3, sanskrit: "तद्वैराग्यादपि दोषबीजक्षये कैवल्यम्", transliteration: "tad-vairāgyād api doṣa-bīja-kṣaye kaivalyam", english: "By non-attachment even to that (omniscience and lordship), the seeds of affliction are destroyed, and liberation (kaivalya) is attained.", commentary: "Even these supreme attainments must be renounced. Only by letting go of siddhis themselves does the yogi reach kaivalya." },
  { id: "3.52", number: 52, pada: 3, sanskrit: "स्थान्युपनिमन्त्रणे सङ्गस्मयाकरणं पुनरनिष्टप्रसङ्गात्", transliteration: "sthāny-upanimantraṇe saṅga-smayākaraṇaṁ punar aniṣṭa-prasaṅgāt", english: "When invited by celestial beings (to take higher positions), the yogi should neither feel attached nor proud, for there is a risk of falling back.", commentary: "A crucial warning: even divine invitations should be met with indifference by the yogi, as attachment to heavenly rewards perpetuates bondage." },
  { id: "3.53", number: 53, pada: 3, sanskrit: "क्षणतत्क्रमयोः संयमाद्विवेकजं ज्ञानम्", transliteration: "kṣaṇa-tat-kramayoḥ saṃyamād vivekajaṁ jñānam", english: "By saṃyama on the moment (kṣaṇa) and its sequence (krama), knowledge born of discriminative discernment (viveka) arises.", commentary: "Perceiving the ultimate, indivisible moments of time and their sequence gives rise to direct discriminative knowledge of reality." },
  { id: "3.54", number: 54, pada: 3, sanskrit: "जातिलक्षणदेशैरन्यतानवच्छेदात्तुल्ययोस्ततः प्रतिपत्तिः", transliteration: "jāti-lakṣaṇa-deśair anyatānavacchedāt tulyayos tataḥ pratipattiḥ", english: "By that (vivekaja-jñāna), one can distinguish between two similar objects that cannot be distinguished by species, characteristic, or position.", commentary: "This discriminative knowledge can differentiate even identical objects, transcending ordinary perception." },
  { id: "3.55", number: 55, pada: 3, sanskrit: "तारकं सर्वविषयं सर्वथाविषयमक्रमं चेति विवेकजं ज्ञानम्", transliteration: "tārakaṁ sarva-viṣayaṁ sarvathā-viṣayam akramaṁ ceti vivekajaṁ jñānam", english: "The knowledge born of discrimination (viveka-jñāna) is transcendent (tārakam), pertaining to all objects simultaneously, and beyond sequential order.", commentary: "This highest knowledge is tārakam — saving, liberating. It knows all objects at once, without the limitation of temporal sequence." },
]

// ── Pada 4: Kaivalya Pada (34 sutras) ────────────────────────────────
const kaivalyaPadaVerses: YogaSutraVerse[] = [
  { id: "4.1", number: 1, pada: 4, sanskrit: "जन्मौषधिमन्त्रतपःसमाधिजाः सिद्धयः", transliteration: "janmauṣadhi-mantra-tapaḥ-samādhi-jāḥ siddhayaḥ", english: "Psychic powers (siddhis) arise from: birth, herbs, mantras, austerity, or samādhi.", commentary: "Siddhis can be obtained through five means: by birth (genetic/disposition), through herbs (plants/substances), by mantra (sacred sounds), through tapas (austerity), or through samādhi (meditative absorption). Those attained through samādhi are considered most stable." },
  { id: "4.2", number: 2, pada: 4, sanskrit: "जात्यन्तरपरिणामः प्रकृत्यापूरात्", transliteration: "jāty-antara-pariṇāmaḥ prakṛty-āpūrāt", english: "The transformation from one species or state to another occurs through the natural fullness of cause and effect.", commentary: "Evolution from one form to another is a natural process driven by prakṛti's inherent creative impulse." },
  { id: "4.3", number: 3, pada: 4, sanskrit: "निमित्तमप्रयोजकं प्रकृतीनां वरणभेदस्तु ततः क्षेत्रिकवत्", transliteration: "nimittam aprayojakaṁ prakṛtīnāṁ varaṇa-bhedas tu tataḥ kṣetrikavat", english: "The efficient cause (the yogi's effort) does not directly set prakṛti in motion; it removes the obstacles, like a farmer clearing a canal.", commentary: "The yogi's efforts do not directly create change but remove obstacles, allowing the natural flow of transformation — like a farmer opening a water channel." },
  { id: "4.4", number: 4, pada: 4, sanskrit: "निर्माणचित्तान्यस्मितामात्रात्", transliteration: "nirmāṇa-cittāny asmitā-mātrāt", english: "Created minds (nirmāṇa-citta) arise only from the sense of 'I' (asmitā).", commentary: "The yogi can create multiple minds/identities, all grounded in the subtle ego (asmitā)." },
  { id: "4.5", number: 5, pada: 4, sanskrit: "प्रवृत्तिभेदे प्रयोजकं चित्तमेकमनेकेषाम्", transliteration: "pravṛtti-bhede prayojakaṁ cittam ekam anekeṣām", english: "Though there are many minds, one original mind directs their various activities.", commentary: "One fundamental consciousness directs the activities of the many created minds." },
  { id: "4.6", number: 6, pada: 4, sanskrit: "तत्र ध्यानजमनाशयम्", transliteration: "tatra dhyānajam anāśayam", english: "Among these (siddhis), those born of meditation (dhyāna) are without the seed of karmic residue.", commentary: "Siddhis attained through meditation do not create karmic bonds, unlike those acquired through birth, herbs, etc." },
  { id: "4.7", number: 7, pada: 4, sanskrit: "कर्माशुक्लाकृष्णं योगिनस्त्रिविधमितरेषाम्", transliteration: "karmāśukla-kṛṣṇaṁ yoginas trividham itareṣām", english: "The karma of a yogi is neither white nor black; for others, it is of three kinds: white, black, or mixed.", commentary: "The liberated yogi's actions produce no karmic traces. Ordinary people's actions are either virtuous (white), non-virtuous (black), or mixed." },
  { id: "4.8", number: 8, pada: 4, sanskrit: "ततस्तद्विपाकानुगुणानामेवाभिव्यक्तिर्वासनानाम्", transliteration: "tatas tad-vipākānuguṇānām evābhivyaktir vāsanānām", english: "From that, only those vāsanās (latent tendencies) manifest whose conditions for fruition are suitable.", commentary: "Of the accumulated karmic tendencies, only those whose time for manifestation has come become active." },
  { id: "4.9", number: 9, pada: 4, sanskrit: "जातिदेशकालव्यवहितानामप्यानन्तर्यं स्मृतिसंस्कारयोरेकरूपत्वात्", transliteration: "jāti-deśa-kāla-vyavahitānām apy ānantaryaṁ smṛti-saṃskārayor eka-rūpatvāt", english: "Even when separated by birth, place, or time, memory and latent impressions remain connected due to the continuity of their nature.", commentary: "Karmic impressions and their memory persist across lifetimes, despite gaps in birth, location, or time." },
  { id: "4.10", number: 10, pada: 4, sanskrit: "तासामनादित्वं चाशिषो नित्यत्वात्", transliteration: "tāsām anāditvaṁ cāśiṣo nityatvāt", english: "These vāsanās are beginningless, because the will-to-live (āśiṣa) is eternal.", commentary: "The karmic tendencies have no beginning, driven by the eternal, innate desire for existence." },
  { id: "4.11", number: 11, pada: 4, sanskrit: "हेतुफलाश्रयालम्बनैः संगृहीतत्वादेषामभावे तदभावः", transliteration: "hetu-phalāśrayālambanaiḥ saṅgṛhītatvād eṣām abhāve tad-abhāvaḥ", english: "Vāsanās are held together by cause (hetu), effect (phala), substrate (āśraya), and support (ālambana). When these are absent, they too are absent.", commentary: "For vāsanās to function, four factors must be present. When these are removed — through yoga — the vāsanās dissolve." },
  { id: "4.12", number: 12, pada: 4, sanskrit: "अतीतानागतं स्वरूपतोऽस्त्यध्वभेदाद्धर्माणाम्", transliteration: "atītānāgataṁ svarūpato 'sty adhva-bhedād dharmāṇām", english: "The past and the future exist in their own essential nature, differing only in the stage of their manifestation.", commentary: "Past, present, and future are not absolute but relative — they are different phases in the manifestation of qualities (dharmas)." },
  { id: "4.13", number: 13, pada: 4, sanskrit: "ते व्यक्तसूक्ष्मा गुणात्मानः", transliteration: "te vyakta-sūkṣmā guṇātmānaḥ", english: "They (the dharmas) are manifested or subtle, consisting of the three guṇas.", commentary: "All qualities are expressions of the three guṇas — sattva, rajas, and tamas — in either manifest (vyakta) or subtle (sūkṣma) forms." },
  { id: "4.14", number: 14, pada: 4, sanskrit: "परिणामैकत्वाद्वस्तुतत्त्वम्", transliteration: "pariṇāmaikatvād vastu-tattvam", english: "The identity of an object is determined by the unity of its transformations.", commentary: "An object is recognized as the same despite changes because its transformations form a unified sequence." },
  { id: "4.15", number: 15, pada: 4, sanskrit: "वस्तुसाम्ये चित्तभेदादयोर्भिन्नाः पथाः", transliteration: "vastu-sāmye citta-bhedād ayor bhinnāḥ pathāḥ", english: "Even when the object is the same, different minds perceive it differently, proving the diversity of perception.", commentary: "The same object is perceived differently by different minds, showing that perception is subjective — a key distinction between object (Prakṛti) and subject (Puruṣa)." },
  { id: "4.16", number: 16, pada: 4, sanskrit: "न चैकचित्ततन्त्रं वस्तु तदप्रमाणकं तदा किं स्यात्", transliteration: "na caika-citta-tantraṁ vastu tad-apramāṇakaṁ tadā kiṁ syāt", english: "An object does not depend on one mind's perception. If it did, what would happen when that mind does not perceive it?", commentary: "Objects have an independent existence beyond any single mind's perception. This refutes pure solipsism." },
  { id: "4.17", number: 17, pada: 4, sanskrit: "तदुपरागापेक्षित्वाच्चित्तस्य वस्तु ज्ञाताज्ञातम्", transliteration: "tad-uparāgāpekṣitvāc cittasya vastu jñātājñātam", english: "An object is known or unknown depending on whether the mind is colored (affected) by it.", commentary: "Knowledge of an object depends on the mind's connection to it. If the mind is not affected, the object remains unknown." },
  { id: "4.18", number: 18, pada: 4, sanskrit: "सदा ज्ञाताश्चित्तवृत्तयस्तत्प्रभोः पुरुषस्यापरिणामित्वात्", transliteration: "sadā jñātāś citta-vṛttayas tat-prabhoḥ puruṣasyāpariṇāmitvāt", english: "The modifications of the mind are always known to its Lord (Puruṣa), because Puruṣa is immutable.", commentary: "Puruṣa (pure consciousness) is the eternal witness — it always knows the mind's activities because it is unchanging and therefore never unaware." },
  { id: "4.19", number: 19, pada: 4, sanskrit: "न तत्स्वाभासं दृश्यत्वात्", transliteration: "na tat-svābhāsaṁ dṛśyatvāt", english: "The mind is not self-luminous, because it is itself an object of perception.", commentary: "The mind can be observed/witnessed, so it cannot be the ultimate subject — it is itself an object of awareness." },
  { id: "4.20", number: 20, pada: 4, sanskrit: "एकसमये चोभयानवधारणम्", transliteration: "eka-samaye cobhayānavadhāraṇam", english: "And the mind cannot perceive two things simultaneously — itself and an external object.", commentary: "The mind cannot simultaneously be the perceiver and perceive itself — this indicates that there is a higher consciousness witnessing the mind." },
  { id: "4.21", number: 21, pada: 4, sanskrit: "चित्तान्तरदृश्ये बुद्धिबुद्धेरतिप्रसङ्गः स्मृतिसङ्करश्च", transliteration: "cittāntara-dṛśye buddhi-buddher atiprasaṅgaḥ smṛti-saṅkaraś ca", english: "If one mind were perceived by another mind, then there would be an infinite regress of perceived minds and confusion of memory.", commentary: "The theory that one mind perceives another leads to infinite regress (one mind perceived by another, that by another, etc.). This proves the existence of Puruṣa as the ultimate Seer." },
  { id: "4.22", number: 22, pada: 4, sanskrit: "चितेरप्रतिसंक्रमायास्तदाकारापत्तौ स्वबुद्धिसंवेदनम्", transliteration: "citer apratisaṅkramāyās tad-ākārāpattau sva-buddhi-saṃvedanam", english: "Though consciousness (citi) is immutable, when it takes the form of the mind (buddhi), it appears to be aware of its own mental states.", commentary: "Puruṣa (consciousness) is unchanging but appears to perceive the mind's states by taking on the mind's coloring through the conjunction of Seer and Seen." },
  { id: "4.23", number: 23, pada: 4, sanskrit: "द्रष्टृदृश्योपरक्तं चित्तं सर्वार्थम्", transliteration: "draṣṭṛ-dṛśyoparaktaṁ cittaṁ sarvārtham", english: "The mind, colored by both the Seer (draṣṭṛ) and the Seen (dṛśya), apprehends all objects.", commentary: "The mind serves as the meeting point of consciousness and the world — reflecting both the Puruṣa and objects." },
  { id: "4.24", number: 24, pada: 4, sanskrit: "तदसंख्येयवासनाभिश्चित्रमपि परार्थं संहत्यकारित्वात्", transliteration: "tad asaṅkhyeya-vāsanābhiś citram api parārthaṁ saṁhatya-kāritvāt", english: "Though the mind is variegated with countless vāsanās, it exists for another (Puruṣa), because it acts in combination.", commentary: "The mind's complex structure serves the Puruṣa — it is an instrument, not the ultimate subject." },
  { id: "4.25", number: 25, pada: 4, sanskrit: "विशेषदर्शिन आत्मभावभावनानिवृत्तिः", transliteration: "viśeṣa-darśina ātma-bhāva-bhāvanā-nivṛttiḥ", english: "For the one who perceives the distinction (between mind and Puruṣa), the false identification of the Self with the mind ceases.", commentary: "The direct perception of the difference between Puruṣa and mind ends all further speculation about one's true nature." },
  { id: "4.26", number: 26, pada: 4, sanskrit: "तदा विवेकनिम्नं कैवल्यप्राग्भारं चित्तम्", transliteration: "tadā viveka-nimnaṁ kaivalya-prāgbhāraṁ cittam", english: "Then, the mind inclines toward discriminative wisdom (viveka) and gravitates toward liberation (kaivalya).", commentary: "With the end of false identification, the mind naturally flows toward the discriminative distinction that leads to liberation." },
  { id: "4.27", number: 27, pada: 4, sanskrit: "तच्छिद्रेषु प्रत्ययान्तराणि संस्कारेभ्यः", transliteration: "tac-chidreṣu pratyayāntarāṇi saṃskārebhyaḥ", english: "In the gaps (of this discriminative habit), other thoughts arise from latent impressions (saṃskāras).", commentary: "When the yogi's attention to discrimination wavers, old karmic impressions create distractions — constant vigilance is needed." },
  { id: "4.28", number: 28, pada: 4, sanskrit: "हानमेषां क्लेशवदुक्तम्", transliteration: "hānam eṣāṁ kleśavad uktam", english: "The removal of these (distractions) is achieved as in the case of the kleśas — through pratipakṣa-bhāvanā (cultivating the opposite).", commentary: "Just as the kleśas (afflictions) are overcome by cultivating their opposites, so too are these saṃskāra-induced distractions." },
  { id: "4.29", number: 29, pada: 4, sanskrit: "प्रसङ्ख्यानेऽप्यकुसीदस्य विवेकख्यातिर्धर्ममेघः समाधिः", transliteration: "prasaṅkhyāne 'py akusīdasya viveka-khyātir dharma-meghaḥ samādhiḥ", english: "For one who remains disinterested even in the highest knowledge, the cloud of dharma (dharma-megha) samādhi arises — a rain of virtue.", commentary: "When even the bliss of discriminative knowledge is renounced, the yogi attains dharma-megha samādhi — a 'cloud of virtue' that showers liberation." },
  { id: "4.30", number: 30, pada: 4, sanskrit: "ततः क्लेशकर्मनिवृत्तिः", transliteration: "tataḥ kleśa-karma-nivṛttiḥ", english: "From that (dharma-megha samādhi), the cessation of afflictions (kleśas) and karma occurs.", commentary: "In dharma-megha samādhi, all kleśas are destroyed, and no new karma is created." },
  { id: "4.31", number: 31, pada: 4, sanskrit: "तदा सर्वावरणमलापेतस्य ज्ञानस्यानन्त्यात्ज्ञेयमल्पम्", transliteration: "tadā sarvāvaraṇa-malāpetasya jñānasyānantyāj jñeyam alpam", english: "Then, when all veils and impurities are removed, knowledge becomes infinite, and what remains to be known is little.", commentary: "When the obstacles to knowledge are removed, the scope of wisdom is infinite — all knowable reality is comprehended." },
  { id: "4.32", number: 32, pada: 4, sanskrit: "ततः कृतार्थानां परिणामक्रमसमाप्तिर्गुणानाम्", transliteration: "tataḥ kṛtārthānāṁ pariṇāma-krama-samāptir guṇānām", english: "Then, the sequence of transformations of the guṇas, having fulfilled their purpose, comes to an end.", commentary: "The three guṇas (sattva, rajas, tamas) cease their transformations because their purpose — providing experience and liberation for the Puruṣa — has been accomplished." },
  { id: "4.33", number: 33, pada: 4, sanskrit: "क्षणप्रतियोगी परिणामापरान्तनिर्ग्राह्यः क्रमः", transliteration: "kṣaṇa-pratiyogī pariṇāmāparānta-nirgrāhyaḥ kramaḥ", english: "The sequence (krama) of moments — which corresponds to the final stage of transformation — is comprehended as a series of discrete, indivisible moments.", commentary: "Time is perceived as a sequence of discrete moments (kṣaṇas), and the entire process of change is grasped in its ultimate nature." },
  { id: "4.34", number: 34, pada: 4, sanskrit: "पुरुषार्थशून्यानां गुणानां प्रतिप्रसवः कैवल्यं स्वरूपप्रतिष्ठा वा चितिशक्तिरिति", transliteration: "puruṣārtha-śūnyānāṁ guṇānāṁ pratiprasavaḥ kaivalyaṁ sva-rūpa-pratiṣṭhā vā citi-śaktir iti", english: "Liberation (kaivalya) is the resolution of the guṇas, which have become devoid of purpose for the Puruṣa, and the abiding of consciousness (citi-śakti) in its own true nature.", commentary: "This final sutra of the Yoga Sutras defines kaivalya as the ultimate state: when the guṇas return to their source, having fulfilled their purpose, and the Puruṣa stands in its own essential nature — pure, liberated consciousness." }
]

// ── Assemble all padas ────────────────────────────────────────────────
export const yogaPadas: YogaPada[] = [
  {
    id: "samadhi",
    number: 1,
    name: "Samadhi Pada",
    sanskritName: "समाधि पाद",
    transliteration: "Samādhi Pāda",
    summary: "The first chapter defines Yoga as the cessation of the mind's modifications. It describes the nature of the mind, the obstacles to Yoga, and the various methods — including practice, detachment, and devotion to Īśvara — by which samādhi (complete absorption) is attained. The chapter culminates in the description of seedless (nirbīja) samādhi, the highest state of absorption.",
    theme: "The nature of consciousness, the modifications of the mind, and the path to complete mental absorption (samādhi).",
    verses: samadhiPadaVerses,
  },
  {
    id: "sadhana",
    number: 2,
    name: "Sadhana Pada",
    sanskritName: "साधन पाद",
    transliteration: "Sādhana Pāda",
    summary: "The second chapter presents the practical path of Yoga. It introduces kriyā-yoga (the yoga of action), the five kleśas (afflictions) that cause suffering, and the eight-limbed path (aṣṭāṅga yoga). The first five limbs — yama, niyama, āsana, prāṇāyāma, and pratyāhāra — are explained in detail as the external aids to Yoga.",
    theme: "The practical path of Yoga — the afflictions, kriyā-yoga, and the first five limbs of aṣṭāṅga yoga.",
    verses: sadhanaPadaVerses,
  },
  {
    id: "vibhuti",
    number: 3,
    name: "Vibhuti Pada",
    sanskritName: "विभूति पाद",
    transliteration: "Vibhūti Pāda",
    summary: "The third chapter focuses on saṃyama — the combined practice of dhāraṇā (concentration), dhyāna (meditation), and samādhi (absorption). Through saṃyama on various aspects of reality, the yogi attains extraordinary powers (vibhūtis or siddhis). However, Patañjali warns that these powers are obstacles to the ultimate goal of kaivalya.",
    theme: "The internal limbs of Yoga, the practice of saṃyama, and the attainment of psychic powers (siddhis).",
    verses: vibhutiPadaVerses,
  },
  {
    id: "kaivalya",
    number: 4,
    name: "Kaivalya Pada",
    sanskritName: "कैवल्य पाद",
    transliteration: "Kaivalya Pāda",
    summary: "The fourth and final chapter describes the nature of liberation (kaivalya). It discusses the causes of siddhis, the nature of karma and vāsanās, the distinction between the mind (citta) and pure consciousness (Puruṣa), and the final state of kaivalya where the guṇas cease their activity and the Puruṣa abides in its own true nature.",
    theme: "The nature of liberation (kaivalya), the distinction between mind and consciousness, and the final cessation of the guṇas.",
    verses: kaivalyaPadaVerses,
  },
]

// ── Helper: flat list of all verses for compatibility ─────────────────
export const allYogaSutraVerses: YogaSutraVerse[] = [
  ...samadhiPadaVerses,
  ...sadhanaPadaVerses,
  ...vibhutiPadaVerses,
  ...kaivalyaPadaVerses,
]

// ── Helper functions ──────────────────────────────────────────────────
export function getYogaPada(padaId: string): YogaPada | undefined {
  return yogaPadas.find((p) => p.id === padaId)
}

export function getYogaPadaByNumber(num: number): YogaPada | undefined {
  return yogaPadas.find((p) => p.number === num)
}

export function getYogaSutra(id: string): YogaSutraVerse | undefined {
  return allYogaSutraVerses.find((v) => v.id === id)
}

export const yogaSutrasInfo = {
  title: "Yoga Sutras of Patanjali",
  sanskritTitle: "पातञ्जलयोगसूत्राणि",
  transliteration: "Pātañjalayogasūtrāṇi",
  author: "Maharishi Patanjali",
  period: "~400-200 BCE (classical period)",
  verseCount: allYogaSutraVerses.length,
  padaCount: yogaPadas.length,
  summary: "The Yoga Sutras of Patanjali is the foundational text of Classical Yoga philosophy. It presents a complete system for achieving liberation (kaivalya) through the systematic practice of the eight limbs of yoga. The text covers the nature of the mind, the causes of suffering, the path of practice, and the ultimate state of liberation.",
  theme: "The nature of consciousness, the path of yoga, the attainment of powers, and final liberation (kaivalya).",
}
