#!/usr/bin/env python3
"""
Regenerate src/lib/gita-data.ts from:
  1. The original source backup's chapter metadata (from generate_gita.py)
  2. The live deployment's verse data including commentary (from verses_live.json)

Output: /home/z/my-project/src/lib/gita-data.ts (overwrites existing)

The output preserves the exact structure of the original gita-data.ts:
  - Verse interface gets a new `commentary?: string` field
  - Each verse object has the commentary field added (or omitted if placeholder)
"""
import json
import os
import sys
import re

# Read the original gita-data.ts to get chapter metadata
ORIG_GITA_PATH = "/home/z/my-project/recovery/source_backup/src/lib/gita-data.ts"
LIVE_VERSES_JSON = "/home/z/my-project/recovery/inspections/verses_live.json"
OUT_PATH = "/home/z/my-project/src/lib/gita-data.ts"

# Read original gita-data.ts to extract chapter metadata (number, name, sanskritName, etc.)
print(f"Reading original gita-data.ts from {ORIG_GITA_PATH}")
with open(ORIG_GITA_PATH, 'r', encoding='utf-8') as f:
    orig_content = f.read()

# Read the live verses JSON (700 verses with commentary)
print(f"Reading live verses JSON from {LIVE_VERSES_JSON}")
with open(LIVE_VERSES_JSON, 'r', encoding='utf-8') as f:
    live_verses = json.load(f)

print(f"Loaded {len(live_verses)} verses from live JSON")

# Index verses by chapter
verses_by_chapter = {}
for v in live_verses:
    chap = v['chapter']
    verses_by_chapter.setdefault(chap, []).append(v)

# Extract chapter metadata from the original file using regex
# Pattern: { number: N, name: "...", sanskritName: "...", transliteration: "...", verseCount: N, theme: "...", summary: "...", verses: [ ... ] }
# We'll use the Python generator script instead — it has clean chapter metadata

# Actually, parse the chapter metadata directly from orig_content
# Look for the chapter object pattern
chapter_pattern = re.compile(
    r'\{\s*'
    r'number:\s*(\d+),\s*'
    r'name:\s*"([^"]+)",\s*'
    r'sanskritName:\s*"([^"]+)",\s*'
    r'transliteration:\s*"([^"]+)",\s*'
    r'verseCount:\s*(\d+),\s*'
    r'theme:\s*"([^"]+)",\s*'
    r'summary:\s*"((?:[^"\\]|\\.)*)",\s*'
    r'verses:\s*\['
)

chapters_meta = []
for m in chapter_pattern.finditer(orig_content):
    chapters_meta.append({
        'number': int(m.group(1)),
        'name': m.group(2),
        'sanskritName': m.group(3),
        'transliteration': m.group(4),
        'verseCount': int(m.group(5)),
        'theme': m.group(6),
        'summary': m.group(7).encode().decode('unicode_escape'),
    })

print(f"Extracted metadata for {len(chapters_meta)} chapters")
print(f"  Chapter 1: {chapters_meta[0]['name']}")
print(f"  Chapter 18: {chapters_meta[-1]['name']}")


def js_string(s: str) -> str:
    """Escape a Python string as a JS double-quoted string literal."""
    if s is None:
        return '""'
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            out.append('\\r')
        elif ch == '\t':
            out.append('\\t')
        elif ord(ch) < 0x20:
            out.append('\\u{:04x}'.format(ord(ch)))
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


# Build the new TypeScript file
lines = []
lines.append('// Auto-generated by /home/z/my-project/scripts/regenerate_gita_data.py')
lines.append('// Source: live deployment JS bundle (700 verses with commentary)')
lines.append('// DO NOT EDIT MANUALLY — edit the script and re-run instead.')
lines.append('//')
lines.append('// Bhagavad Gita — Complete: all 18 chapters, all 700 verses.')
lines.append('// Sanskrit: standard Devanagari text.')
lines.append('// Transliteration: IAST (International Alphabet of Sanskrit Transliteration).')
lines.append('// English: clear modern rendering based on standard translations.')
lines.append('// Commentary: Swami Mukundananda commentary (where available).')
lines.append('')
lines.append('export interface Verse {')
lines.append('  id: string')
lines.append('  chapter: number')
lines.append('  verse: number')
lines.append('  sanskrit: string')
lines.append('  transliteration: string')
lines.append('  english: string')
lines.append('  meaning?: string')
lines.append('  commentary?: string')
lines.append('}')
lines.append('')
lines.append('export interface Chapter {')
lines.append('  number: number')
lines.append('  name: string')
lines.append('  sanskritName: string')
lines.append('  transliteration: string')
lines.append('  verseCount: number')
lines.append('  summary: string')
lines.append('  theme: string')
lines.append('  verses: Verse[]')
lines.append('}')
lines.append('')
lines.append('export const gitaChapters: Chapter[] = [')

for chap_meta in chapters_meta:
    chap_num = chap_meta['number']
    verses = verses_by_chapter.get(chap_num, [])
    # Sort verses by verse number
    verses = sorted(verses, key=lambda v: v['verse'])

    lines.append('  {')
    lines.append(f'    number: {chap_num},')
    lines.append(f'    name: {js_string(chap_meta["name"])},')
    lines.append(f'    sanskritName: {js_string(chap_meta["sanskritName"])},')
    lines.append(f'    transliteration: {js_string(chap_meta["transliteration"])},')
    lines.append(f'    verseCount: {chap_meta["verseCount"]},')
    lines.append(f'    theme: {js_string(chap_meta["theme"])},')
    lines.append(f'    summary: {js_string(chap_meta["summary"])},')
    lines.append('    verses: [')
    for v in verses:
        parts = []
        parts.append(f'id: {js_string(v["id"])}')
        parts.append(f'chapter: {v["chapter"]}')
        parts.append(f'verse: {v["verse"]}')
        parts.append(f'sanskrit: {js_string(v["sanskrit"])}')
        parts.append(f'transliteration: {js_string(v["transliteration"])}')
        parts.append(f'english: {js_string(v["english"])}')
        meaning = v.get('meaning')
        if meaning:
            parts.append(f'meaning: {js_string(meaning)}')
        commentary = v.get('commentary')
        # Skip the placeholder text — treat as no commentary
        if commentary and commentary.strip() != '(Commentary not available for this verse)':
            parts.append(f'commentary: {js_string(commentary)}')
        lines.append('      { ' + ', '.join(parts) + ' },')
    lines.append('    ],')
    lines.append('  },')

lines.append(']')
lines.append('')

# Add helper exports from the original file
lines.append('export const allVerses: Verse[] = gitaChapters.flatMap((c) => c.verses)')
lines.append('')
lines.append('export const totalVerseCount = gitaChapters.reduce(')
lines.append('  (sum, c) => sum + c.verseCount, 0);')
lines.append('')
lines.append('export function getChapter(num: number): Chapter | undefined {')
lines.append('  return gitaChapters.find((c) => c.number === num)')
lines.append('}')
lines.append('')
lines.append('export function getVerse(id: string): Verse | undefined {')
lines.append('  return allVerses.find((v) => v.id === id)')
lines.append('}')
lines.append('')
lines.append('export const findVersesByKeyword = (keyword: string): Verse[] => {')
lines.append('  const kw = keyword.toLowerCase().trim();')
lines.append('  if (!kw) return [];')
lines.append('  return allVerses.filter(')
lines.append('    (v) =>')
lines.append('      v.english.toLowerCase().includes(kw) ||')
lines.append('      v.transliteration.toLowerCase().includes(kw) ||')
lines.append('      (v.meaning ?? "").toLowerCase().includes(kw) ||')
lines.append('      (v.commentary ?? "").toLowerCase().includes(kw),')
lines.append('  );')
lines.append('};')
lines.append('')
lines.append('// Topic index for keyword search shortcuts')
lines.append('export const topicIndex: { topic: string; verseIds: string[]; description: string }[] = [')

# Read the topic index from the original file
topic_pattern = re.compile(
    r'\{\s*topic:\s*"([^"]+)",\s*'
    r'verseIds:\s*\[([^\]]+)\],\s*'
    r'description:\s*"((?:[^"\\]|\\.)*)"\s*'
    r'\}'
)
topic_section_match = re.search(r'export const topicIndex:.*?\[\s*(.*?)\s*\]\s*;', orig_content, re.DOTALL)
if topic_section_match:
    topic_section = topic_section_match.group(1)
    for m in topic_pattern.finditer(topic_section):
        topic = m.group(1)
        verse_ids_raw = m.group(2)
        description = m.group(3).encode().decode('unicode_escape')
        # Parse verse IDs
        verse_ids = re.findall(r'"([^"]+)"', verse_ids_raw)
        lines.append(f'  {{ topic: {js_string(topic)}, verseIds: [{", ".join(js_string(vid) for vid in verse_ids)}], description: {js_string(description)} }},')
lines.append(']')

# Write the file
output = '\n'.join(lines) + '\n'
print(f"\nWriting {len(output)} bytes to {OUT_PATH}")
with open(OUT_PATH, 'w', encoding='utf-8') as f:
    f.write(output)
print(f"Done! {len(live_verses)} verses across {len(chapters_meta)} chapters written.")
